replicaCount: 1
account: service-general-sa
namespace: dev
nameOverride: ~
image:
  repository:  {{.image}}
  tag: {{.tag}}
  pullPolicy: IfNotPresent
service:
  name: mrs-service-cab-connector-catalog
  type: ClusterIP
  configuration:
    format: yaml
    provider: k8s
  ports:
    grpc:
      protocol: TCP
      externalPort: 8098
      internalPort: 8098
  internal:
    retail:
      endpoint: //mrs-service-retail:3000
      cache:
        purgeCycle: 5
        ttl: 86400
    authApi:
      endpoint: //mrs-service-connector-cab-api:8090
  external:
    baseURI: X
    resources:
      stockprice:
        path: /stock
      label:
        path: /price
k8sSidecar:
  image: 170546463463.dkr.ecr.eu-west-1.amazonaws.com/k8s-sidecar:1.0.0-rc.4
  port: 50051
resources:
  requests:
    memory: "64Mi"
    cpu: "10m"
  limits:
    memory: "768Mi"
    cpu: "50m"