replicaCount: 1
account: service-general-sa
namespace: dev
nameOverride: ~
image:
  repository:  {{.image}}
  tag: {{.tag}}
  pullPolicy: IfNotPresent
service:
  name: mrs-service-cab-connector-auth
  type: ClusterIP
  configuration:
    format: yaml
    provider: k8s
  ports:
    grpc:
      protocol: TCP
      externalPort: 8095
      internalPort: 8095
  external:
    baseURI: X
    resources:
      auth:
        path: /login
connectorApi:
  image: 170546463463.dkr.ecr.eu-west-1.amazonaws.com/mrs-service-connector-api:v2.0.0-build.0
  ports:
    apihttp:
      protocol: TCP
      externalPort: 8080
      internalPort: 8080
    apigrpc:
      protocol: TCP
      externalPort: 8090
      internalPort: 8090
k8sSidecar:
  image: 170546463463.dkr.ecr.eu-west-1.amazonaws.com/k8s-sidecar:1.0.0-rc.4
  port: 50051
resources:
  requests:
    memory: "64Mi"
    cpu: "10m"
  limits:
    memory: "768Mi"
    cpu: "50m"