// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth_types.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c58156effca98b81, []int{0}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthResponse struct {
	RefreshToken         string   `protobuf:"bytes,1,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	TokenType            string   `protobuf:"bytes,2,opt,name=tokenType,proto3" json:"tokenType,omitempty"`
	AccessToken          string   `protobuf:"bytes,3,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	ExpiresIn            int32    `protobuf:"varint,4,opt,name=expiresIn,proto3" json:"expiresIn,omitempty"`
	Cookie               string   `protobuf:"bytes,5,opt,name=cookie,proto3" json:"cookie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c58156effca98b81, []int{1}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *AuthResponse) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

func (m *AuthResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *AuthResponse) GetExpiresIn() int32 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

func (m *AuthResponse) GetCookie() string {
	if m != nil {
		return m.Cookie
	}
	return ""
}

type AuthResult struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool          `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message              string        `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Result               *AuthResponse `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AuthResult) Reset()         { *m = AuthResult{} }
func (m *AuthResult) String() string { return proto.CompactTextString(m) }
func (*AuthResult) ProtoMessage()    {}
func (*AuthResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_c58156effca98b81, []int{2}
}

func (m *AuthResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResult.Unmarshal(m, b)
}
func (m *AuthResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResult.Marshal(b, m, deterministic)
}
func (m *AuthResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResult.Merge(m, src)
}
func (m *AuthResult) XXX_Size() int {
	return xxx_messageInfo_AuthResult.Size(m)
}
func (m *AuthResult) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResult.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResult proto.InternalMessageInfo

func (m *AuthResult) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AuthResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AuthResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AuthResult) GetResult() *AuthResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

type GetUserStoresRequest struct {
	GrantedStores        string   `protobuf:"bytes,1,opt,name=grantedStores,proto3" json:"grantedStores,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserStoresRequest) Reset()         { *m = GetUserStoresRequest{} }
func (m *GetUserStoresRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserStoresRequest) ProtoMessage()    {}
func (*GetUserStoresRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c58156effca98b81, []int{3}
}

func (m *GetUserStoresRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserStoresRequest.Unmarshal(m, b)
}
func (m *GetUserStoresRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserStoresRequest.Marshal(b, m, deterministic)
}
func (m *GetUserStoresRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserStoresRequest.Merge(m, src)
}
func (m *GetUserStoresRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserStoresRequest.Size(m)
}
func (m *GetUserStoresRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserStoresRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserStoresRequest proto.InternalMessageInfo

func (m *GetUserStoresRequest) GetGrantedStores() string {
	if m != nil {
		return m.GrantedStores
	}
	return ""
}

func (m *GetUserStoresRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetUserStoresResult struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool              `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message              string            `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Result               []*StoresResponse `protobuf:"bytes,4,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetUserStoresResult) Reset()         { *m = GetUserStoresResult{} }
func (m *GetUserStoresResult) String() string { return proto.CompactTextString(m) }
func (*GetUserStoresResult) ProtoMessage()    {}
func (*GetUserStoresResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_c58156effca98b81, []int{4}
}

func (m *GetUserStoresResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserStoresResult.Unmarshal(m, b)
}
func (m *GetUserStoresResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserStoresResult.Marshal(b, m, deterministic)
}
func (m *GetUserStoresResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserStoresResult.Merge(m, src)
}
func (m *GetUserStoresResult) XXX_Size() int {
	return xxx_messageInfo_GetUserStoresResult.Size(m)
}
func (m *GetUserStoresResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserStoresResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserStoresResult proto.InternalMessageInfo

func (m *GetUserStoresResult) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetUserStoresResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetUserStoresResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetUserStoresResult) GetResult() []*StoresResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

type StoresResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoresResponse) Reset()         { *m = StoresResponse{} }
func (m *StoresResponse) String() string { return proto.CompactTextString(m) }
func (*StoresResponse) ProtoMessage()    {}
func (*StoresResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c58156effca98b81, []int{5}
}

func (m *StoresResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoresResponse.Unmarshal(m, b)
}
func (m *StoresResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoresResponse.Marshal(b, m, deterministic)
}
func (m *StoresResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoresResponse.Merge(m, src)
}
func (m *StoresResponse) XXX_Size() int {
	return xxx_messageInfo_StoresResponse.Size(m)
}
func (m *StoresResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StoresResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StoresResponse proto.InternalMessageInfo

func (m *StoresResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StoresResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetTokenWithoutCredentialsRequest struct {
	OldToken             string   `protobuf:"bytes,1,opt,name=old_token,json=oldToken,proto3" json:"old_token,omitempty"`
	Cookie               string   `protobuf:"bytes,2,opt,name=cookie,proto3" json:"cookie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenWithoutCredentialsRequest) Reset()         { *m = GetTokenWithoutCredentialsRequest{} }
func (m *GetTokenWithoutCredentialsRequest) String() string { return proto.CompactTextString(m) }
func (*GetTokenWithoutCredentialsRequest) ProtoMessage()    {}
func (*GetTokenWithoutCredentialsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c58156effca98b81, []int{6}
}

func (m *GetTokenWithoutCredentialsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenWithoutCredentialsRequest.Unmarshal(m, b)
}
func (m *GetTokenWithoutCredentialsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenWithoutCredentialsRequest.Marshal(b, m, deterministic)
}
func (m *GetTokenWithoutCredentialsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenWithoutCredentialsRequest.Merge(m, src)
}
func (m *GetTokenWithoutCredentialsRequest) XXX_Size() int {
	return xxx_messageInfo_GetTokenWithoutCredentialsRequest.Size(m)
}
func (m *GetTokenWithoutCredentialsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenWithoutCredentialsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenWithoutCredentialsRequest proto.InternalMessageInfo

func (m *GetTokenWithoutCredentialsRequest) GetOldToken() string {
	if m != nil {
		return m.OldToken
	}
	return ""
}

func (m *GetTokenWithoutCredentialsRequest) GetCookie() string {
	if m != nil {
		return m.Cookie
	}
	return ""
}

type GetUserInfoRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoRequest) Reset()         { *m = GetUserInfoRequest{} }
func (m *GetUserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoRequest) ProtoMessage()    {}
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c58156effca98b81, []int{7}
}

func (m *GetUserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoRequest.Unmarshal(m, b)
}
func (m *GetUserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetUserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoRequest.Merge(m, src)
}
func (m *GetUserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoRequest.Size(m)
}
func (m *GetUserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoRequest proto.InternalMessageInfo

func (m *GetUserInfoRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetUserInfoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetUserInfoResult struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool                 `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message              string               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Result               *GetUserInfoResponse `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetUserInfoResult) Reset()         { *m = GetUserInfoResult{} }
func (m *GetUserInfoResult) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoResult) ProtoMessage()    {}
func (*GetUserInfoResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_c58156effca98b81, []int{8}
}

func (m *GetUserInfoResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoResult.Unmarshal(m, b)
}
func (m *GetUserInfoResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoResult.Marshal(b, m, deterministic)
}
func (m *GetUserInfoResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoResult.Merge(m, src)
}
func (m *GetUserInfoResult) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoResult.Size(m)
}
func (m *GetUserInfoResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoResult proto.InternalMessageInfo

func (m *GetUserInfoResult) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetUserInfoResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetUserInfoResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetUserInfoResult) GetResult() *GetUserInfoResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

type GetUserInfoResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            string   `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	OrganizationId       string   `protobuf:"bytes,6,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ApplicationId        string   `protobuf:"bytes,7,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Roles                []string `protobuf:"bytes,8,rep,name=roles,proto3" json:"roles,omitempty"`
	Language             string   `protobuf:"bytes,9,opt,name=language,proto3" json:"language,omitempty"`
	Status               string   `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoResponse) Reset()         { *m = GetUserInfoResponse{} }
func (m *GetUserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoResponse) ProtoMessage()    {}
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c58156effca98b81, []int{9}
}

func (m *GetUserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoResponse.Unmarshal(m, b)
}
func (m *GetUserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetUserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoResponse.Merge(m, src)
}
func (m *GetUserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoResponse.Size(m)
}
func (m *GetUserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoResponse proto.InternalMessageInfo

func (m *GetUserInfoResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetUserInfoResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetUserInfoResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *GetUserInfoResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetUserInfoResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetUserInfoResponse) GetOrganizationId() string {
	if m != nil {
		return m.OrganizationId
	}
	return ""
}

func (m *GetUserInfoResponse) GetApplicationId() string {
	if m != nil {
		return m.ApplicationId
	}
	return ""
}

func (m *GetUserInfoResponse) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *GetUserInfoResponse) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *GetUserInfoResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthRequest)(nil), "proto.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "proto.AuthResponse")
	proto.RegisterType((*AuthResult)(nil), "proto.AuthResult")
	proto.RegisterType((*GetUserStoresRequest)(nil), "proto.GetUserStoresRequest")
	proto.RegisterType((*GetUserStoresResult)(nil), "proto.GetUserStoresResult")
	proto.RegisterType((*StoresResponse)(nil), "proto.StoresResponse")
	proto.RegisterType((*GetTokenWithoutCredentialsRequest)(nil), "proto.GetTokenWithoutCredentialsRequest")
	proto.RegisterType((*GetUserInfoRequest)(nil), "proto.GetUserInfoRequest")
	proto.RegisterType((*GetUserInfoResult)(nil), "proto.GetUserInfoResult")
	proto.RegisterType((*GetUserInfoResponse)(nil), "proto.GetUserInfoResponse")
}

func init() { proto.RegisterFile("auth_types.proto", fileDescriptor_c58156effca98b81) }

var fileDescriptor_c58156effca98b81 = []byte{
	// 537 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0x9d, 0x8f, 0x26, 0x93, 0x12, 0x60, 0x5b, 0x90, 0x55, 0x40, 0x0a, 0x16, 0x88, 0x48,
	0x88, 0x1e, 0x02, 0x3f, 0x80, 0x08, 0xa1, 0x2a, 0xd7, 0x50, 0x44, 0x6f, 0xd1, 0x92, 0x9d, 0x26,
	0xab, 0x3a, 0x5e, 0xb3, 0x3b, 0x16, 0x14, 0x89, 0x3b, 0x12, 0x7f, 0x84, 0x1b, 0x7f, 0x11, 0x79,
	0x77, 0x9d, 0x78, 0xd3, 0x4b, 0x0f, 0x3d, 0x25, 0xef, 0x3d, 0x7b, 0xe6, 0xcd, 0x9b, 0x31, 0x3c,
	0xe0, 0x25, 0xad, 0x17, 0x74, 0x5d, 0xa0, 0x39, 0x2d, 0xb4, 0x22, 0xc5, 0x3a, 0xf6, 0x27, 0xfd,
	0x08, 0x83, 0x69, 0x49, 0xeb, 0x39, 0x7e, 0x2b, 0xd1, 0x10, 0x3b, 0x81, 0x5e, 0x69, 0x50, 0xe7,
	0x7c, 0x83, 0x49, 0x34, 0x8a, 0xc6, 0xfd, 0xf9, 0x16, 0x57, 0x5a, 0xc1, 0x8d, 0xf9, 0xae, 0xb4,
	0x48, 0x62, 0xa7, 0xd5, 0x38, 0xfd, 0x1b, 0xc1, 0xa1, 0xab, 0x63, 0x0a, 0x95, 0x1b, 0x64, 0x29,
	0x1c, 0x6a, 0xbc, 0xd4, 0x68, 0xd6, 0xe7, 0xea, 0x0a, 0x73, 0x5f, 0x2c, 0xe0, 0xd8, 0x53, 0xe8,
	0x53, 0xf5, 0xe7, 0xfc, 0xba, 0x40, 0x5f, 0x71, 0x47, 0xb0, 0x11, 0x0c, 0xf8, 0x72, 0x89, 0xc6,
	0xb8, 0x02, 0x2d, 0xab, 0x37, 0xa9, 0xea, 0x7d, 0xfc, 0x51, 0x48, 0x8d, 0x66, 0x96, 0x27, 0xed,
	0x51, 0x34, 0xee, 0xcc, 0x77, 0x04, 0x7b, 0x0c, 0xdd, 0xa5, 0x52, 0x57, 0x12, 0x93, 0x8e, 0x7d,
	0xd5, 0xa3, 0xf4, 0x17, 0x80, 0x77, 0x5a, 0x66, 0xc4, 0x86, 0x10, 0x4b, 0xe1, 0xdd, 0xc5, 0x52,
	0xb0, 0x04, 0x0e, 0x4c, 0x69, 0x7b, 0x58, 0x47, 0xbd, 0x79, 0x0d, 0x2b, 0x65, 0x83, 0xc6, 0xf0,
	0x15, 0x7a, 0x2f, 0x35, 0x64, 0xaf, 0xa1, 0xab, 0x6d, 0x35, 0x6b, 0x62, 0x30, 0x39, 0x72, 0x11,
	0x9f, 0x36, 0x03, 0x99, 0xfb, 0x47, 0xd2, 0x0b, 0x38, 0x3e, 0x43, 0xfa, 0x6c, 0x50, 0x7f, 0x22,
	0xa5, 0xd1, 0xd4, 0xc9, 0xbf, 0x80, 0x7b, 0x2b, 0xcd, 0x73, 0x42, 0xe1, 0x78, 0xef, 0x29, 0x24,
	0x83, 0xfd, 0xc4, 0xe1, 0x7e, 0xd2, 0xdf, 0x11, 0x1c, 0xed, 0x95, 0xbe, 0xb3, 0x11, 0xdf, 0x34,
	0x46, 0x6c, 0x8d, 0x07, 0x93, 0x47, 0x7e, 0xc4, 0x6d, 0xa3, 0x70, 0xc8, 0x77, 0x30, 0x0c, 0x95,
	0x1b, 0x26, 0x18, 0xb4, 0x1b, 0x43, 0xd8, 0xff, 0xe9, 0x05, 0x3c, 0x3f, 0x43, 0xb2, 0xbb, 0xfd,
	0x22, 0x69, 0xad, 0x4a, 0xfa, 0xa0, 0x51, 0x60, 0x4e, 0x92, 0x67, 0xdb, 0x9c, 0x9e, 0x40, 0x5f,
	0x65, 0x62, 0x41, 0x8d, 0xab, 0xea, 0xa9, 0x4c, 0xb8, 0x8b, 0xd8, 0xed, 0x3c, 0x0e, 0x76, 0xfe,
	0x1e, 0x98, 0x4f, 0x66, 0x96, 0x5f, 0xaa, 0xdb, 0x1c, 0xbb, 0xf3, 0x1b, 0xd7, 0x7e, 0xd3, 0x3f,
	0x11, 0x3c, 0x0c, 0x4a, 0xdc, 0x59, 0xb4, 0x93, 0xbd, 0xeb, 0x39, 0xf1, 0xd1, 0x86, 0xdd, 0xc2,
	0x7c, 0xff, 0xc5, 0xdb, 0x55, 0x37, 0xf5, 0x1b, 0x7e, 0x9e, 0x01, 0x2c, 0x35, 0x72, 0x42, 0xb1,
	0xe0, 0x54, 0x7f, 0x62, 0x9e, 0x99, 0x52, 0x25, 0x97, 0x85, 0xa8, 0x65, 0xe7, 0xab, 0xef, 0x99,
	0x69, 0x98, 0x4f, 0x7b, 0x2f, 0x9f, 0x63, 0xe8, 0xe0, 0x86, 0xcb, 0xcc, 0x7f, 0x5c, 0x0e, 0xb0,
	0x57, 0x70, 0x5f, 0xe9, 0x15, 0xcf, 0xe5, 0x4f, 0x4e, 0x52, 0xe5, 0x0b, 0x29, 0x92, 0xae, 0xd5,
	0x87, 0x4d, 0x7a, 0x26, 0xd8, 0x4b, 0x18, 0xf2, 0xa2, 0xc8, 0xe4, 0x72, 0xfb, 0xdc, 0x81, 0x3b,
	0xf7, 0x06, 0x3b, 0x13, 0x55, 0x17, 0xad, 0x32, 0x34, 0x49, 0x6f, 0xd4, 0xaa, 0xba, 0x58, 0x50,
	0xf9, 0xca, 0x78, 0xbe, 0x2a, 0xab, 0x30, 0xfb, 0xce, 0x57, 0x8d, 0xab, 0x0b, 0x30, 0xc4, 0xa9,
	0x34, 0x09, 0xb8, 0x0b, 0x70, 0xe8, 0x6b, 0xd7, 0x86, 0xfa, 0xf6, 0x7f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xa7, 0x21, 0x3a, 0x14, 0x09, 0x05, 0x00, 0x00,
}
