// Code generated by protoc-gen-go. DO NOT EDIT.
// source: label_types.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request
type GetLabelRequest struct {
	Store                string   `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Sku                  string   `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	Ean                  string   `protobuf:"bytes,4,opt,name=ean,proto3" json:"ean,omitempty"`
	Pvp                  string   `protobuf:"bytes,5,opt,name=pvp,proto3" json:"pvp,omitempty"`
	OldPrice             string   `protobuf:"bytes,6,opt,name=old_price,json=oldPrice,proto3" json:"old_price,omitempty"`
	Discount             string   `protobuf:"bytes,7,opt,name=discount,proto3" json:"discount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLabelRequest) Reset()         { *m = GetLabelRequest{} }
func (m *GetLabelRequest) String() string { return proto.CompactTextString(m) }
func (*GetLabelRequest) ProtoMessage()    {}
func (*GetLabelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf64213384c1565b, []int{0}
}

func (m *GetLabelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLabelRequest.Unmarshal(m, b)
}
func (m *GetLabelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLabelRequest.Marshal(b, m, deterministic)
}
func (m *GetLabelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLabelRequest.Merge(m, src)
}
func (m *GetLabelRequest) XXX_Size() int {
	return xxx_messageInfo_GetLabelRequest.Size(m)
}
func (m *GetLabelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLabelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLabelRequest proto.InternalMessageInfo

func (m *GetLabelRequest) GetStore() string {
	if m != nil {
		return m.Store
	}
	return ""
}

func (m *GetLabelRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *GetLabelRequest) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *GetLabelRequest) GetEan() string {
	if m != nil {
		return m.Ean
	}
	return ""
}

func (m *GetLabelRequest) GetPvp() string {
	if m != nil {
		return m.Pvp
	}
	return ""
}

func (m *GetLabelRequest) GetOldPrice() string {
	if m != nil {
		return m.OldPrice
	}
	return ""
}

func (m *GetLabelRequest) GetDiscount() string {
	if m != nil {
		return m.Discount
	}
	return ""
}

// Response
type LabelResponse struct {
	Code                 string            `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Data                 map[string]string `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LabelResponse) Reset()         { *m = LabelResponse{} }
func (m *LabelResponse) String() string { return proto.CompactTextString(m) }
func (*LabelResponse) ProtoMessage()    {}
func (*LabelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf64213384c1565b, []int{1}
}

func (m *LabelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LabelResponse.Unmarshal(m, b)
}
func (m *LabelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LabelResponse.Marshal(b, m, deterministic)
}
func (m *LabelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LabelResponse.Merge(m, src)
}
func (m *LabelResponse) XXX_Size() int {
	return xxx_messageInfo_LabelResponse.Size(m)
}
func (m *LabelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LabelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LabelResponse proto.InternalMessageInfo

func (m *LabelResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *LabelResponse) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetLabelResult struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool           `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message              string         `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Result               *LabelResponse `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetLabelResult) Reset()         { *m = GetLabelResult{} }
func (m *GetLabelResult) String() string { return proto.CompactTextString(m) }
func (*GetLabelResult) ProtoMessage()    {}
func (*GetLabelResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf64213384c1565b, []int{2}
}

func (m *GetLabelResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLabelResult.Unmarshal(m, b)
}
func (m *GetLabelResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLabelResult.Marshal(b, m, deterministic)
}
func (m *GetLabelResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLabelResult.Merge(m, src)
}
func (m *GetLabelResult) XXX_Size() int {
	return xxx_messageInfo_GetLabelResult.Size(m)
}
func (m *GetLabelResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLabelResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetLabelResult proto.InternalMessageInfo

func (m *GetLabelResult) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetLabelResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetLabelResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetLabelResult) GetResult() *LabelResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*GetLabelRequest)(nil), "proto.GetLabelRequest")
	proto.RegisterType((*LabelResponse)(nil), "proto.LabelResponse")
	proto.RegisterMapType((map[string]string)(nil), "proto.LabelResponse.DataEntry")
	proto.RegisterType((*GetLabelResult)(nil), "proto.GetLabelResult")
}

func init() { proto.RegisterFile("label_types.proto", fileDescriptor_bf64213384c1565b) }

var fileDescriptor_bf64213384c1565b = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x4b, 0x33, 0x31,
	0x10, 0xc6, 0xc9, 0xf6, 0xff, 0x94, 0xb7, 0xaf, 0x86, 0x1e, 0x42, 0x05, 0x29, 0x3d, 0xf5, 0x20,
	0x3d, 0xd4, 0x83, 0xe2, 0x59, 0xf1, 0xe2, 0x41, 0xf6, 0x0b, 0x94, 0x74, 0x33, 0xc8, 0xd2, 0xb8,
	0x89, 0x3b, 0x49, 0x61, 0xaf, 0x7e, 0x02, 0x3f, 0x87, 0x9f, 0x52, 0x92, 0xec, 0x5a, 0x05, 0x4f,
	0x99, 0xe7, 0x37, 0x99, 0xe1, 0x99, 0x07, 0xce, 0xb5, 0xdc, 0xa3, 0xde, 0xb9, 0xc6, 0x22, 0x6d,
	0x6c, 0x6d, 0x9c, 0xe1, 0x83, 0xf8, 0xac, 0x3e, 0x19, 0xfc, 0x7f, 0x44, 0xf7, 0x14, 0xfa, 0x39,
	0xbe, 0x79, 0x24, 0xc7, 0xe7, 0x30, 0x20, 0x67, 0x6a, 0x14, 0x6c, 0xc9, 0xd6, 0x93, 0x3c, 0x09,
	0xce, 0xa1, 0x5f, 0x18, 0x85, 0x22, 0x8b, 0x30, 0xd6, 0xfc, 0x0c, 0x7a, 0x74, 0xf0, 0xa2, 0x17,
	0x51, 0x28, 0x03, 0x41, 0x59, 0x89, 0x7e, 0x22, 0x28, 0xab, 0x40, 0xec, 0xd1, 0x8a, 0x41, 0x22,
	0xf6, 0x68, 0xf9, 0x05, 0x4c, 0x8c, 0x56, 0x3b, 0x5b, 0x97, 0x05, 0x8a, 0x61, 0xe4, 0x63, 0xa3,
	0xd5, 0x73, 0xd0, 0x7c, 0x01, 0x63, 0x55, 0x52, 0x61, 0x7c, 0xe5, 0xc4, 0x28, 0xf5, 0x3a, 0xbd,
	0xfa, 0x60, 0xf0, 0xaf, 0x75, 0x4a, 0xd6, 0x54, 0x74, 0x32, 0xc5, 0x7e, 0x98, 0xda, 0x42, 0x5f,
	0x49, 0x27, 0x45, 0xb6, 0xec, 0xad, 0xa7, 0xdb, 0xcb, 0x74, 0xef, 0xe6, 0xd7, 0xdc, 0xe6, 0x5e,
	0x3a, 0xf9, 0x50, 0xb9, 0xba, 0xc9, 0xe3, 0xdf, 0xc5, 0x0d, 0x4c, 0xbe, 0x51, 0x70, 0x7c, 0xc0,
	0xa6, 0xdd, 0x19, 0xca, 0x90, 0xc8, 0x51, 0x6a, 0xdf, 0x1d, 0x9f, 0xc4, 0x5d, 0x76, 0xcb, 0x56,
	0xef, 0x0c, 0x66, 0xa7, 0xfc, 0xc8, 0x6b, 0xc7, 0x67, 0x90, 0x95, 0xaa, 0x9d, 0xce, 0x4a, 0xc5,
	0x05, 0x8c, 0xc8, 0x17, 0x05, 0x12, 0xc5, 0xf1, 0x71, 0xde, 0xc9, 0xd0, 0x79, 0x45, 0x22, 0xf9,
	0x82, 0x6d, 0x84, 0x9d, 0xe4, 0x57, 0x30, 0xac, 0xe3, 0xb6, 0x98, 0xe4, 0x74, 0x3b, 0xff, 0xeb,
	0x8a, 0xbc, 0xfd, 0xb3, 0x1f, 0xc6, 0xe6, 0xf5, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x11,
	0x09, 0xd9, 0xe7, 0x01, 0x00, 0x00,
}
