// Code generated by protoc-gen-go. DO NOT EDIT.
// source: process_task.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContainerSummary struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerSummary) Reset()         { *m = ContainerSummary{} }
func (m *ContainerSummary) String() string { return proto.CompactTextString(m) }
func (*ContainerSummary) ProtoMessage()    {}
func (*ContainerSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff11d3bf0f73436, []int{0}
}

func (m *ContainerSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerSummary.Unmarshal(m, b)
}
func (m *ContainerSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerSummary.Marshal(b, m, deterministic)
}
func (m *ContainerSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerSummary.Merge(m, src)
}
func (m *ContainerSummary) XXX_Size() int {
	return xxx_messageInfo_ContainerSummary.Size(m)
}
func (m *ContainerSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerSummary.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerSummary proto.InternalMessageInfo

type SourceSummary struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          *wrappers.StringValue `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SourceSummary) Reset()         { *m = SourceSummary{} }
func (m *SourceSummary) String() string { return proto.CompactTextString(m) }
func (*SourceSummary) ProtoMessage()    {}
func (*SourceSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff11d3bf0f73436, []int{1}
}

func (m *SourceSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceSummary.Unmarshal(m, b)
}
func (m *SourceSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceSummary.Marshal(b, m, deterministic)
}
func (m *SourceSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceSummary.Merge(m, src)
}
func (m *SourceSummary) XXX_Size() int {
	return xxx_messageInfo_SourceSummary.Size(m)
}
func (m *SourceSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceSummary.DiscardUnknown(m)
}

var xxx_messageInfo_SourceSummary proto.InternalMessageInfo

func (m *SourceSummary) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SourceSummary) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

type LocationSummary struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          *wrappers.StringValue `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *LocationSummary) Reset()         { *m = LocationSummary{} }
func (m *LocationSummary) String() string { return proto.CompactTextString(m) }
func (*LocationSummary) ProtoMessage()    {}
func (*LocationSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff11d3bf0f73436, []int{2}
}

func (m *LocationSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationSummary.Unmarshal(m, b)
}
func (m *LocationSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationSummary.Marshal(b, m, deterministic)
}
func (m *LocationSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationSummary.Merge(m, src)
}
func (m *LocationSummary) XXX_Size() int {
	return xxx_messageInfo_LocationSummary.Size(m)
}
func (m *LocationSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationSummary.DiscardUnknown(m)
}

var xxx_messageInfo_LocationSummary proto.InternalMessageInfo

func (m *LocationSummary) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LocationSummary) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

type ReasonSummary struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          *wrappers.StringValue `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ReasonSummary) Reset()         { *m = ReasonSummary{} }
func (m *ReasonSummary) String() string { return proto.CompactTextString(m) }
func (*ReasonSummary) ProtoMessage()    {}
func (*ReasonSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff11d3bf0f73436, []int{3}
}

func (m *ReasonSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReasonSummary.Unmarshal(m, b)
}
func (m *ReasonSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReasonSummary.Marshal(b, m, deterministic)
}
func (m *ReasonSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReasonSummary.Merge(m, src)
}
func (m *ReasonSummary) XXX_Size() int {
	return xxx_messageInfo_ReasonSummary.Size(m)
}
func (m *ReasonSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_ReasonSummary.DiscardUnknown(m)
}

var xxx_messageInfo_ReasonSummary proto.InternalMessageInfo

func (m *ReasonSummary) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReasonSummary) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

type LabelInfo struct {
	LabelCode            string   `protobuf:"bytes,1,opt,name=label_code,json=labelCode,proto3" json:"label_code,omitempty"`
	Mandatory            bool     `protobuf:"varint,2,opt,name=mandatory,proto3" json:"mandatory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LabelInfo) Reset()         { *m = LabelInfo{} }
func (m *LabelInfo) String() string { return proto.CompactTextString(m) }
func (*LabelInfo) ProtoMessage()    {}
func (*LabelInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff11d3bf0f73436, []int{4}
}

func (m *LabelInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LabelInfo.Unmarshal(m, b)
}
func (m *LabelInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LabelInfo.Marshal(b, m, deterministic)
}
func (m *LabelInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LabelInfo.Merge(m, src)
}
func (m *LabelInfo) XXX_Size() int {
	return xxx_messageInfo_LabelInfo.Size(m)
}
func (m *LabelInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LabelInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LabelInfo proto.InternalMessageInfo

func (m *LabelInfo) GetLabelCode() string {
	if m != nil {
		return m.LabelCode
	}
	return ""
}

func (m *LabelInfo) GetMandatory() bool {
	if m != nil {
		return m.Mandatory
	}
	return false
}

type Attribute struct {
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Attribute_BoolValue
	//	*Attribute_StrValue
	//	*Attribute_IntValue
	//	*Attribute_FloatValue
	Value                isAttribute_Value `protobuf_oneof:"value"`
	Description          string            `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Attribute) Reset()         { *m = Attribute{} }
func (m *Attribute) String() string { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()    {}
func (*Attribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff11d3bf0f73436, []int{5}
}

func (m *Attribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attribute.Unmarshal(m, b)
}
func (m *Attribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attribute.Marshal(b, m, deterministic)
}
func (m *Attribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attribute.Merge(m, src)
}
func (m *Attribute) XXX_Size() int {
	return xxx_messageInfo_Attribute.Size(m)
}
func (m *Attribute) XXX_DiscardUnknown() {
	xxx_messageInfo_Attribute.DiscardUnknown(m)
}

var xxx_messageInfo_Attribute proto.InternalMessageInfo

func (m *Attribute) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type isAttribute_Value interface {
	isAttribute_Value()
}

type Attribute_BoolValue struct {
	BoolValue *wrappers.BoolValue `protobuf:"bytes,2,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Attribute_StrValue struct {
	StrValue *wrappers.StringValue `protobuf:"bytes,3,opt,name=str_value,json=strValue,proto3,oneof"`
}

type Attribute_IntValue struct {
	IntValue *wrappers.Int64Value `protobuf:"bytes,4,opt,name=int_value,json=intValue,proto3,oneof"`
}

type Attribute_FloatValue struct {
	FloatValue *wrappers.FloatValue `protobuf:"bytes,5,opt,name=float_value,json=floatValue,proto3,oneof"`
}

func (*Attribute_BoolValue) isAttribute_Value() {}

func (*Attribute_StrValue) isAttribute_Value() {}

func (*Attribute_IntValue) isAttribute_Value() {}

func (*Attribute_FloatValue) isAttribute_Value() {}

func (m *Attribute) GetValue() isAttribute_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Attribute) GetBoolValue() *wrappers.BoolValue {
	if x, ok := m.GetValue().(*Attribute_BoolValue); ok {
		return x.BoolValue
	}
	return nil
}

func (m *Attribute) GetStrValue() *wrappers.StringValue {
	if x, ok := m.GetValue().(*Attribute_StrValue); ok {
		return x.StrValue
	}
	return nil
}

func (m *Attribute) GetIntValue() *wrappers.Int64Value {
	if x, ok := m.GetValue().(*Attribute_IntValue); ok {
		return x.IntValue
	}
	return nil
}

func (m *Attribute) GetFloatValue() *wrappers.FloatValue {
	if x, ok := m.GetValue().(*Attribute_FloatValue); ok {
		return x.FloatValue
	}
	return nil
}

func (m *Attribute) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Attribute) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Attribute_BoolValue)(nil),
		(*Attribute_StrValue)(nil),
		(*Attribute_IntValue)(nil),
		(*Attribute_FloatValue)(nil),
	}
}

type Zone struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          *wrappers.StringValue `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Attributes           []*Attribute          `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Zone) Reset()         { *m = Zone{} }
func (m *Zone) String() string { return proto.CompactTextString(m) }
func (*Zone) ProtoMessage()    {}
func (*Zone) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff11d3bf0f73436, []int{6}
}

func (m *Zone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Zone.Unmarshal(m, b)
}
func (m *Zone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Zone.Marshal(b, m, deterministic)
}
func (m *Zone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Zone.Merge(m, src)
}
func (m *Zone) XXX_Size() int {
	return xxx_messageInfo_Zone.Size(m)
}
func (m *Zone) XXX_DiscardUnknown() {
	xxx_messageInfo_Zone.DiscardUnknown(m)
}

var xxx_messageInfo_Zone proto.InternalMessageInfo

func (m *Zone) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Zone) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *Zone) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type Origin struct {
	Ref                  string   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Sequence             int32    `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Origin) Reset()         { *m = Origin{} }
func (m *Origin) String() string { return proto.CompactTextString(m) }
func (*Origin) ProtoMessage()    {}
func (*Origin) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff11d3bf0f73436, []int{7}
}

func (m *Origin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Origin.Unmarshal(m, b)
}
func (m *Origin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Origin.Marshal(b, m, deterministic)
}
func (m *Origin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Origin.Merge(m, src)
}
func (m *Origin) XXX_Size() int {
	return xxx_messageInfo_Origin.Size(m)
}
func (m *Origin) XXX_DiscardUnknown() {
	xxx_messageInfo_Origin.DiscardUnknown(m)
}

var xxx_messageInfo_Origin proto.InternalMessageInfo

func (m *Origin) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

func (m *Origin) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Origin) GetSequence() int32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

type TaskSummary struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string               `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	StoreId              string               `protobuf:"bytes,3,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Zone                 *Zone                `protobuf:"bytes,4,opt,name=zone,proto3" json:"zone,omitempty"`
	Origin               *Origin              `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty"`
	Source               *SourceSummary       `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Location             *LocationSummary     `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	Reason               *ReasonSummary       `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	AdHoc                *wrappers.BoolValue  `protobuf:"bytes,9,opt,name=ad_hoc,json=adHoc,proto3" json:"ad_hoc,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,10,opt,name=date,proto3" json:"date,omitempty"`
	StartDate            *timestamp.Timestamp `protobuf:"bytes,11,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	StartUser            string               `protobuf:"bytes,12,opt,name=start_user,json=startUser,proto3" json:"start_user,omitempty"`
	FinishDate           *timestamp.Timestamp `protobuf:"bytes,13,opt,name=finish_date,json=finishDate,proto3" json:"finish_date,omitempty"`
	FinishUser           string               `protobuf:"bytes,14,opt,name=finish_user,json=finishUser,proto3" json:"finish_user,omitempty"`
	FirstPickingDate     *timestamp.Timestamp `protobuf:"bytes,15,opt,name=first_picking_date,json=firstPickingDate,proto3" json:"first_picking_date,omitempty"`
	LastPickingDate      *timestamp.Timestamp `protobuf:"bytes,16,opt,name=last_picking_date,json=lastPickingDate,proto3" json:"last_picking_date,omitempty"`
	UpdateUser           string               `protobuf:"bytes,19,opt,name=update_user,json=updateUser,proto3" json:"update_user,omitempty"`
	Metadata             *_struct.Struct      `protobuf:"bytes,17,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Attributes           []*Attribute         `protobuf:"bytes,18,rep,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TaskSummary) Reset()         { *m = TaskSummary{} }
func (m *TaskSummary) String() string { return proto.CompactTextString(m) }
func (*TaskSummary) ProtoMessage()    {}
func (*TaskSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff11d3bf0f73436, []int{8}
}

func (m *TaskSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskSummary.Unmarshal(m, b)
}
func (m *TaskSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskSummary.Marshal(b, m, deterministic)
}
func (m *TaskSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskSummary.Merge(m, src)
}
func (m *TaskSummary) XXX_Size() int {
	return xxx_messageInfo_TaskSummary.Size(m)
}
func (m *TaskSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskSummary.DiscardUnknown(m)
}

var xxx_messageInfo_TaskSummary proto.InternalMessageInfo

func (m *TaskSummary) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TaskSummary) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TaskSummary) GetStoreId() string {
	if m != nil {
		return m.StoreId
	}
	return ""
}

func (m *TaskSummary) GetZone() *Zone {
	if m != nil {
		return m.Zone
	}
	return nil
}

func (m *TaskSummary) GetOrigin() *Origin {
	if m != nil {
		return m.Origin
	}
	return nil
}

func (m *TaskSummary) GetSource() *SourceSummary {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *TaskSummary) GetLocation() *LocationSummary {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *TaskSummary) GetReason() *ReasonSummary {
	if m != nil {
		return m.Reason
	}
	return nil
}

func (m *TaskSummary) GetAdHoc() *wrappers.BoolValue {
	if m != nil {
		return m.AdHoc
	}
	return nil
}

func (m *TaskSummary) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *TaskSummary) GetStartDate() *timestamp.Timestamp {
	if m != nil {
		return m.StartDate
	}
	return nil
}

func (m *TaskSummary) GetStartUser() string {
	if m != nil {
		return m.StartUser
	}
	return ""
}

func (m *TaskSummary) GetFinishDate() *timestamp.Timestamp {
	if m != nil {
		return m.FinishDate
	}
	return nil
}

func (m *TaskSummary) GetFinishUser() string {
	if m != nil {
		return m.FinishUser
	}
	return ""
}

func (m *TaskSummary) GetFirstPickingDate() *timestamp.Timestamp {
	if m != nil {
		return m.FirstPickingDate
	}
	return nil
}

func (m *TaskSummary) GetLastPickingDate() *timestamp.Timestamp {
	if m != nil {
		return m.LastPickingDate
	}
	return nil
}

func (m *TaskSummary) GetUpdateUser() string {
	if m != nil {
		return m.UpdateUser
	}
	return ""
}

func (m *TaskSummary) GetMetadata() *_struct.Struct {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *TaskSummary) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type ResourceSummary struct {
	Sku                  string                `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	ContainerId          string                `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Ean                  string                `protobuf:"bytes,3,opt,name=ean,proto3" json:"ean,omitempty"`
	Quantity             *wrappers.DoubleValue `protobuf:"bytes,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Source               *SourceSummary        `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Location             *LocationSummary      `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	Reason               *ReasonSummary        `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	HierarchyCategory    []string              `protobuf:"bytes,8,rep,name=hierarchy_category,json=hierarchyCategory,proto3" json:"hierarchy_category,omitempty"`
	Metadata             *_struct.Struct       `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Type                 string                `protobuf:"bytes,10,opt,name=type,proto3" json:"type,omitempty"`
	Label                *LabelInfo            `protobuf:"bytes,11,opt,name=label,proto3" json:"label,omitempty"`
	FirstPickingDate     *timestamp.Timestamp  `protobuf:"bytes,12,opt,name=first_picking_date,json=firstPickingDate,proto3" json:"first_picking_date,omitempty"`
	LastPickingDate      *timestamp.Timestamp  `protobuf:"bytes,13,opt,name=last_picking_date,json=lastPickingDate,proto3" json:"last_picking_date,omitempty"`
	Attributes           []*Attribute          `protobuf:"bytes,14,rep,name=attributes,proto3" json:"attributes,omitempty"`
	UpdateUser           string                `protobuf:"bytes,15,opt,name=update_user,json=updateUser,proto3" json:"update_user,omitempty"`
	ExpectedQuantity     *wrappers.DoubleValue `protobuf:"bytes,16,opt,name=expected_quantity,json=expectedQuantity,proto3" json:"expected_quantity,omitempty"`
	Price                *PriceInfo            `protobuf:"bytes,17,opt,name=price,proto3" json:"price,omitempty"`
	ParentId             string                `protobuf:"bytes,18,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	AdHoc                *wrappers.BoolValue   `protobuf:"bytes,19,opt,name=ad_hoc,json=adHoc,proto3" json:"ad_hoc,omitempty"`
	PickingMode          string                `protobuf:"bytes,20,opt,name=picking_mode,json=pickingMode,proto3" json:"picking_mode,omitempty"`
	Action               *wrappers.StringValue `protobuf:"bytes,21,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ResourceSummary) Reset()         { *m = ResourceSummary{} }
func (m *ResourceSummary) String() string { return proto.CompactTextString(m) }
func (*ResourceSummary) ProtoMessage()    {}
func (*ResourceSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff11d3bf0f73436, []int{9}
}

func (m *ResourceSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceSummary.Unmarshal(m, b)
}
func (m *ResourceSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceSummary.Marshal(b, m, deterministic)
}
func (m *ResourceSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceSummary.Merge(m, src)
}
func (m *ResourceSummary) XXX_Size() int {
	return xxx_messageInfo_ResourceSummary.Size(m)
}
func (m *ResourceSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceSummary.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceSummary proto.InternalMessageInfo

func (m *ResourceSummary) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *ResourceSummary) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *ResourceSummary) GetEan() string {
	if m != nil {
		return m.Ean
	}
	return ""
}

func (m *ResourceSummary) GetQuantity() *wrappers.DoubleValue {
	if m != nil {
		return m.Quantity
	}
	return nil
}

func (m *ResourceSummary) GetSource() *SourceSummary {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *ResourceSummary) GetLocation() *LocationSummary {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *ResourceSummary) GetReason() *ReasonSummary {
	if m != nil {
		return m.Reason
	}
	return nil
}

func (m *ResourceSummary) GetHierarchyCategory() []string {
	if m != nil {
		return m.HierarchyCategory
	}
	return nil
}

func (m *ResourceSummary) GetMetadata() *_struct.Struct {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *ResourceSummary) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ResourceSummary) GetLabel() *LabelInfo {
	if m != nil {
		return m.Label
	}
	return nil
}

func (m *ResourceSummary) GetFirstPickingDate() *timestamp.Timestamp {
	if m != nil {
		return m.FirstPickingDate
	}
	return nil
}

func (m *ResourceSummary) GetLastPickingDate() *timestamp.Timestamp {
	if m != nil {
		return m.LastPickingDate
	}
	return nil
}

func (m *ResourceSummary) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *ResourceSummary) GetUpdateUser() string {
	if m != nil {
		return m.UpdateUser
	}
	return ""
}

func (m *ResourceSummary) GetExpectedQuantity() *wrappers.DoubleValue {
	if m != nil {
		return m.ExpectedQuantity
	}
	return nil
}

func (m *ResourceSummary) GetPrice() *PriceInfo {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *ResourceSummary) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *ResourceSummary) GetAdHoc() *wrappers.BoolValue {
	if m != nil {
		return m.AdHoc
	}
	return nil
}

func (m *ResourceSummary) GetPickingMode() string {
	if m != nil {
		return m.PickingMode
	}
	return ""
}

func (m *ResourceSummary) GetAction() *wrappers.StringValue {
	if m != nil {
		return m.Action
	}
	return nil
}

type Expiration struct {
	Type                  string                `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Date                  *timestamp.Timestamp  `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Quantity              *wrappers.Int32Value  `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Depreciation          *wrappers.Int32Value  `protobuf:"bytes,4,opt,name=depreciation,proto3" json:"depreciation,omitempty"`
	Withdrawal            *wrappers.Int32Value  `protobuf:"bytes,5,opt,name=withdrawal,proto3" json:"withdrawal,omitempty"`
	MaxPercentageDiscount *wrappers.StringValue `protobuf:"bytes,6,opt,name=max_percentage_discount,json=maxPercentageDiscount,proto3" json:"max_percentage_discount,omitempty"`
	DiscountValue         *wrappers.StringValue `protobuf:"bytes,7,opt,name=discount_value,json=discountValue,proto3" json:"discount_value,omitempty"`
	DiscountType          *wrappers.StringValue `protobuf:"bytes,8,opt,name=discount_type,json=discountType,proto3" json:"discount_type,omitempty"`
	FinalPrice            *wrappers.StringValue `protobuf:"bytes,9,opt,name=final_price,json=finalPrice,proto3" json:"final_price,omitempty"`
	OldPrice              *wrappers.StringValue `protobuf:"bytes,10,opt,name=old_price,json=oldPrice,proto3" json:"old_price,omitempty"`
	AdHoc                 *wrappers.BoolValue   `protobuf:"bytes,11,opt,name=ad_hoc,json=adHoc,proto3" json:"ad_hoc,omitempty"`
	AlertId               *wrappers.StringValue `protobuf:"bytes,12,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	Sequence              *wrappers.Int32Value  `protobuf:"bytes,13,opt,name=sequence,proto3" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}              `json:"-"`
	XXX_unrecognized      []byte                `json:"-"`
	XXX_sizecache         int32                 `json:"-"`
}

func (m *Expiration) Reset()         { *m = Expiration{} }
func (m *Expiration) String() string { return proto.CompactTextString(m) }
func (*Expiration) ProtoMessage()    {}
func (*Expiration) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff11d3bf0f73436, []int{10}
}

func (m *Expiration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Expiration.Unmarshal(m, b)
}
func (m *Expiration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Expiration.Marshal(b, m, deterministic)
}
func (m *Expiration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Expiration.Merge(m, src)
}
func (m *Expiration) XXX_Size() int {
	return xxx_messageInfo_Expiration.Size(m)
}
func (m *Expiration) XXX_DiscardUnknown() {
	xxx_messageInfo_Expiration.DiscardUnknown(m)
}

var xxx_messageInfo_Expiration proto.InternalMessageInfo

func (m *Expiration) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Expiration) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *Expiration) GetQuantity() *wrappers.Int32Value {
	if m != nil {
		return m.Quantity
	}
	return nil
}

func (m *Expiration) GetDepreciation() *wrappers.Int32Value {
	if m != nil {
		return m.Depreciation
	}
	return nil
}

func (m *Expiration) GetWithdrawal() *wrappers.Int32Value {
	if m != nil {
		return m.Withdrawal
	}
	return nil
}

func (m *Expiration) GetMaxPercentageDiscount() *wrappers.StringValue {
	if m != nil {
		return m.MaxPercentageDiscount
	}
	return nil
}

func (m *Expiration) GetDiscountValue() *wrappers.StringValue {
	if m != nil {
		return m.DiscountValue
	}
	return nil
}

func (m *Expiration) GetDiscountType() *wrappers.StringValue {
	if m != nil {
		return m.DiscountType
	}
	return nil
}

func (m *Expiration) GetFinalPrice() *wrappers.StringValue {
	if m != nil {
		return m.FinalPrice
	}
	return nil
}

func (m *Expiration) GetOldPrice() *wrappers.StringValue {
	if m != nil {
		return m.OldPrice
	}
	return nil
}

func (m *Expiration) GetAdHoc() *wrappers.BoolValue {
	if m != nil {
		return m.AdHoc
	}
	return nil
}

func (m *Expiration) GetAlertId() *wrappers.StringValue {
	if m != nil {
		return m.AlertId
	}
	return nil
}

func (m *Expiration) GetSequence() *wrappers.Int32Value {
	if m != nil {
		return m.Sequence
	}
	return nil
}

type ItemExpiration struct {
	Sku                  string        `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Data                 []*Expiration `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ItemExpiration) Reset()         { *m = ItemExpiration{} }
func (m *ItemExpiration) String() string { return proto.CompactTextString(m) }
func (*ItemExpiration) ProtoMessage()    {}
func (*ItemExpiration) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff11d3bf0f73436, []int{11}
}

func (m *ItemExpiration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemExpiration.Unmarshal(m, b)
}
func (m *ItemExpiration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemExpiration.Marshal(b, m, deterministic)
}
func (m *ItemExpiration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemExpiration.Merge(m, src)
}
func (m *ItemExpiration) XXX_Size() int {
	return xxx_messageInfo_ItemExpiration.Size(m)
}
func (m *ItemExpiration) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemExpiration.DiscardUnknown(m)
}

var xxx_messageInfo_ItemExpiration proto.InternalMessageInfo

func (m *ItemExpiration) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *ItemExpiration) GetData() []*Expiration {
	if m != nil {
		return m.Data
	}
	return nil
}

type ProcessTaskRequest struct {
	Document             *TaskSummary       `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Resources            []*ResourceSummary `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	Expirations          []*ItemExpiration  `protobuf:"bytes,3,rep,name=expirations,proto3" json:"expirations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ProcessTaskRequest) Reset()         { *m = ProcessTaskRequest{} }
func (m *ProcessTaskRequest) String() string { return proto.CompactTextString(m) }
func (*ProcessTaskRequest) ProtoMessage()    {}
func (*ProcessTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff11d3bf0f73436, []int{12}
}

func (m *ProcessTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessTaskRequest.Unmarshal(m, b)
}
func (m *ProcessTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessTaskRequest.Marshal(b, m, deterministic)
}
func (m *ProcessTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessTaskRequest.Merge(m, src)
}
func (m *ProcessTaskRequest) XXX_Size() int {
	return xxx_messageInfo_ProcessTaskRequest.Size(m)
}
func (m *ProcessTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessTaskRequest proto.InternalMessageInfo

func (m *ProcessTaskRequest) GetDocument() *TaskSummary {
	if m != nil {
		return m.Document
	}
	return nil
}

func (m *ProcessTaskRequest) GetResources() []*ResourceSummary {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *ProcessTaskRequest) GetExpirations() []*ItemExpiration {
	if m != nil {
		return m.Expirations
	}
	return nil
}

type ProcessTaskResponse struct {
	Message              string          `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Result               *_struct.Struct `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ProcessTaskResponse) Reset()         { *m = ProcessTaskResponse{} }
func (m *ProcessTaskResponse) String() string { return proto.CompactTextString(m) }
func (*ProcessTaskResponse) ProtoMessage()    {}
func (*ProcessTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff11d3bf0f73436, []int{13}
}

func (m *ProcessTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessTaskResponse.Unmarshal(m, b)
}
func (m *ProcessTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessTaskResponse.Marshal(b, m, deterministic)
}
func (m *ProcessTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessTaskResponse.Merge(m, src)
}
func (m *ProcessTaskResponse) XXX_Size() int {
	return xxx_messageInfo_ProcessTaskResponse.Size(m)
}
func (m *ProcessTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessTaskResponse proto.InternalMessageInfo

func (m *ProcessTaskResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ProcessTaskResponse) GetResult() *_struct.Struct {
	if m != nil {
		return m.Result
	}
	return nil
}

type PriceValue struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PriceValue) Reset()         { *m = PriceValue{} }
func (m *PriceValue) String() string { return proto.CompactTextString(m) }
func (*PriceValue) ProtoMessage()    {}
func (*PriceValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff11d3bf0f73436, []int{14}
}

func (m *PriceValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceValue.Unmarshal(m, b)
}
func (m *PriceValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceValue.Marshal(b, m, deterministic)
}
func (m *PriceValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceValue.Merge(m, src)
}
func (m *PriceValue) XXX_Size() int {
	return xxx_messageInfo_PriceValue.Size(m)
}
func (m *PriceValue) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceValue.DiscardUnknown(m)
}

var xxx_messageInfo_PriceValue proto.InternalMessageInfo

func (m *PriceValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Price struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Price) Reset()         { *m = Price{} }
func (m *Price) String() string { return proto.CompactTextString(m) }
func (*Price) ProtoMessage()    {}
func (*Price) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff11d3bf0f73436, []int{15}
}

func (m *Price) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Price.Unmarshal(m, b)
}
func (m *Price) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Price.Marshal(b, m, deterministic)
}
func (m *Price) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Price.Merge(m, src)
}
func (m *Price) XXX_Size() int {
	return xxx_messageInfo_Price.Size(m)
}
func (m *Price) XXX_DiscardUnknown() {
	xxx_messageInfo_Price.DiscardUnknown(m)
}

var xxx_messageInfo_Price proto.InternalMessageInfo

func (m *Price) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Price) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PriceInfo struct {
	Current              *PriceValue `protobuf:"bytes,1,opt,name=current,proto3" json:"current,omitempty"`
	Previous             *PriceValue `protobuf:"bytes,2,opt,name=previous,proto3" json:"previous,omitempty"`
	Diff                 string      `protobuf:"bytes,3,opt,name=diff,proto3" json:"diff,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PriceInfo) Reset()         { *m = PriceInfo{} }
func (m *PriceInfo) String() string { return proto.CompactTextString(m) }
func (*PriceInfo) ProtoMessage()    {}
func (*PriceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff11d3bf0f73436, []int{16}
}

func (m *PriceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceInfo.Unmarshal(m, b)
}
func (m *PriceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceInfo.Marshal(b, m, deterministic)
}
func (m *PriceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceInfo.Merge(m, src)
}
func (m *PriceInfo) XXX_Size() int {
	return xxx_messageInfo_PriceInfo.Size(m)
}
func (m *PriceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PriceInfo proto.InternalMessageInfo

func (m *PriceInfo) GetCurrent() *PriceValue {
	if m != nil {
		return m.Current
	}
	return nil
}

func (m *PriceInfo) GetPrevious() *PriceValue {
	if m != nil {
		return m.Previous
	}
	return nil
}

func (m *PriceInfo) GetDiff() string {
	if m != nil {
		return m.Diff
	}
	return ""
}

func init() {
	proto.RegisterType((*ContainerSummary)(nil), "proto.ContainerSummary")
	proto.RegisterType((*SourceSummary)(nil), "proto.SourceSummary")
	proto.RegisterType((*LocationSummary)(nil), "proto.LocationSummary")
	proto.RegisterType((*ReasonSummary)(nil), "proto.ReasonSummary")
	proto.RegisterType((*LabelInfo)(nil), "proto.LabelInfo")
	proto.RegisterType((*Attribute)(nil), "proto.Attribute")
	proto.RegisterType((*Zone)(nil), "proto.Zone")
	proto.RegisterType((*Origin)(nil), "proto.Origin")
	proto.RegisterType((*TaskSummary)(nil), "proto.TaskSummary")
	proto.RegisterType((*ResourceSummary)(nil), "proto.ResourceSummary")
	proto.RegisterType((*Expiration)(nil), "proto.Expiration")
	proto.RegisterType((*ItemExpiration)(nil), "proto.ItemExpiration")
	proto.RegisterType((*ProcessTaskRequest)(nil), "proto.ProcessTaskRequest")
	proto.RegisterType((*ProcessTaskResponse)(nil), "proto.ProcessTaskResponse")
	proto.RegisterType((*PriceValue)(nil), "proto.PriceValue")
	proto.RegisterType((*Price)(nil), "proto.Price")
	proto.RegisterType((*PriceInfo)(nil), "proto.PriceInfo")
}

func init() { proto.RegisterFile("process_task.proto", fileDescriptor_eff11d3bf0f73436) }

var fileDescriptor_eff11d3bf0f73436 = []byte{
	// 1372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xdd, 0x72, 0xdb, 0x44,
	0x14, 0x6e, 0xec, 0xd8, 0x96, 0x8e, 0xec, 0xc4, 0xd9, 0xfe, 0x99, 0xb4, 0x25, 0xa9, 0x67, 0xda,
	0xc9, 0x0c, 0xd4, 0x85, 0xb4, 0x43, 0x29, 0x1d, 0xca, 0xb4, 0x29, 0x9d, 0x98, 0x29, 0x43, 0x50,
	0x03, 0x17, 0xdc, 0x88, 0xb5, 0xb4, 0x76, 0x76, 0x22, 0x6b, 0xd5, 0xdd, 0x55, 0x9b, 0xc0, 0x2d,
	0x17, 0xbc, 0x0f, 0x2f, 0xc0, 0x0c, 0x4f, 0xc1, 0xdb, 0x30, 0xfb, 0x23, 0x45, 0x76, 0x6a, 0xac,
	0xce, 0xb4, 0x57, 0xd6, 0xee, 0x7e, 0xdf, 0x39, 0x47, 0x3a, 0xe7, 0x3b, 0x7b, 0x0c, 0x28, 0xe5,
	0x2c, 0x24, 0x42, 0x04, 0x12, 0x8b, 0xe3, 0x41, 0xca, 0x99, 0x64, 0xa8, 0xa1, 0x7f, 0x36, 0x3f,
	0x9e, 0x30, 0x36, 0x89, 0xc9, 0x5d, 0xbd, 0x1a, 0x65, 0xe3, 0xbb, 0x6f, 0x38, 0x4e, 0x53, 0xc2,
	0x85, 0x81, 0x6d, 0x6e, 0xcd, 0x9f, 0x4b, 0x3a, 0x25, 0x42, 0xe2, 0x69, 0x6a, 0x01, 0xd7, 0xe7,
	0x01, 0x42, 0xf2, 0x2c, 0x94, 0xe6, 0xb4, 0x8f, 0xa0, 0xbb, 0xc7, 0x12, 0x89, 0x69, 0x42, 0xf8,
	0xcb, 0x6c, 0x3a, 0xc5, 0xfc, 0xb4, 0x1f, 0x40, 0xe7, 0x25, 0xcb, 0x78, 0x48, 0xec, 0x06, 0x5a,
	0x83, 0x1a, 0x8d, 0x7a, 0x2b, 0xdb, 0x2b, 0x3b, 0xae, 0x5f, 0xa3, 0x11, 0x7a, 0x0c, 0x5e, 0x44,
	0x44, 0xc8, 0x69, 0x2a, 0x29, 0x4b, 0x7a, 0xb5, 0xed, 0x95, 0x1d, 0x6f, 0xf7, 0xfa, 0xc0, 0x38,
	0x1a, 0xe4, 0x8e, 0x06, 0x2f, 0x25, 0xa7, 0xc9, 0xe4, 0x67, 0x1c, 0x67, 0xc4, 0x2f, 0x13, 0xfa,
	0x18, 0xd6, 0x5f, 0xb0, 0x10, 0xab, 0xe7, 0x0f, 0xe5, 0x22, 0x80, 0x8e, 0x4f, 0xb0, 0xf8, 0x70,
	0x0e, 0xf6, 0xc1, 0x7d, 0x81, 0x47, 0x24, 0x1e, 0x26, 0x63, 0x86, 0x6e, 0x00, 0xc4, 0x6a, 0x11,
	0x84, 0x2c, 0x22, 0xd6, 0x89, 0xab, 0x77, 0xf6, 0x58, 0x44, 0xd0, 0x75, 0x70, 0xa7, 0x38, 0x89,
	0xb0, 0x64, 0xfc, 0x54, 0x7b, 0x72, 0xfc, 0xb3, 0x8d, 0xfe, 0xdf, 0x35, 0x70, 0x9f, 0x48, 0xc9,
	0xe9, 0x28, 0x93, 0x04, 0x21, 0x58, 0x2d, 0x19, 0xd1, 0xcf, 0xe8, 0x11, 0xc0, 0x88, 0xb1, 0x38,
	0x78, 0xad, 0xc2, 0xb0, 0xa1, 0x6e, 0x9e, 0x0b, 0xf5, 0x29, 0x63, 0xb1, 0x0e, 0x74, 0xff, 0x82,
	0xef, 0x8e, 0xf2, 0x05, 0x7a, 0x04, 0xae, 0x90, 0xdc, 0x72, 0xeb, 0xcb, 0x5f, 0x73, 0xff, 0x82,
	0xef, 0x08, 0xc9, 0x0d, 0xf9, 0x2b, 0x70, 0x69, 0x22, 0x2d, 0x79, 0x55, 0x93, 0xaf, 0x9d, 0x23,
	0x0f, 0x13, 0xf9, 0xc5, 0xfd, 0x82, 0x4b, 0x13, 0x69, 0xb8, 0x8f, 0xc1, 0x1b, 0xc7, 0x0c, 0xe7,
	0xec, 0xc6, 0x02, 0xf6, 0x73, 0x85, 0xc9, 0xd9, 0x30, 0x2e, 0x56, 0x68, 0x7b, 0x36, 0x43, 0x4d,
	0xfd, 0x41, 0xca, 0x5b, 0x4f, 0x5b, 0xd0, 0xd0, 0xb6, 0xfb, 0x7f, 0xae, 0xc0, 0xea, 0x2f, 0x2c,
	0x21, 0xef, 0x3b, 0xcb, 0xe8, 0x33, 0x00, 0x9c, 0xa7, 0x46, 0xf4, 0xea, 0xdb, 0xf5, 0x1d, 0x6f,
	0xb7, 0x6b, 0x78, 0x83, 0x22, 0x67, 0x7e, 0x09, 0xd3, 0xff, 0x0e, 0x9a, 0x3f, 0x70, 0x3a, 0xa1,
	0x09, 0xea, 0x42, 0x9d, 0x93, 0xb1, 0x0d, 0x46, 0x3d, 0xaa, 0xdc, 0xca, 0xd3, 0xd4, 0x64, 0xd0,
	0xf5, 0xf5, 0x33, 0xda, 0x04, 0x47, 0x90, 0x57, 0x19, 0x49, 0x42, 0x93, 0x9d, 0x86, 0x5f, 0xac,
	0xfb, 0xff, 0x36, 0xc1, 0x3b, 0xc4, 0xe2, 0x78, 0x51, 0x0d, 0xbf, 0xcd, 0xde, 0x47, 0xe0, 0x08,
	0xc9, 0x38, 0x09, 0x68, 0xa4, 0xed, 0xb9, 0x7e, 0x4b, 0xaf, 0x87, 0x11, 0xda, 0x82, 0xd5, 0xdf,
	0x58, 0x92, 0xe7, 0xd1, 0xb3, 0xaf, 0xa1, 0xbe, 0x9b, 0xaf, 0x0f, 0xd0, 0x2d, 0x68, 0x32, 0x1d,
	0xbb, 0x4d, 0x56, 0xc7, 0x42, 0xcc, 0x0b, 0xf9, 0xf6, 0x10, 0x7d, 0x0a, 0x4d, 0xa1, 0xfb, 0x83,
	0xce, 0x89, 0xb7, 0x7b, 0xc9, 0xc2, 0x66, 0x9a, 0x86, 0x6f, 0x31, 0x68, 0x17, 0x9c, 0xd8, 0x8a,
	0xbd, 0xd7, 0xd2, 0xf8, 0x2b, 0x16, 0x3f, 0xd7, 0x03, 0xfc, 0x02, 0xa7, 0x3c, 0x70, 0xad, 0xde,
	0x9e, 0x33, 0xe3, 0x61, 0x46, 0xd2, 0xbe, 0xc5, 0xa0, 0xcf, 0xa1, 0x89, 0xa3, 0xe0, 0x88, 0x85,
	0x3d, 0x77, 0x99, 0x34, 0xfc, 0x06, 0x8e, 0xf6, 0x59, 0x88, 0x06, 0xb0, 0x1a, 0x61, 0x49, 0x7a,
	0xb0, 0x80, 0x70, 0x98, 0x37, 0x51, 0x5f, 0xe3, 0xd0, 0x43, 0x00, 0x21, 0x31, 0x97, 0x81, 0x66,
	0x79, 0x4b, 0x59, 0xae, 0x46, 0x3f, 0x53, 0xd4, 0x1b, 0x39, 0x35, 0x13, 0x84, 0xf7, 0xda, 0xa6,
	0x37, 0xe8, 0x9d, 0x9f, 0x04, 0xe1, 0xe8, 0x11, 0x78, 0x63, 0x9a, 0x50, 0x71, 0x64, 0x4c, 0x77,
	0x96, 0x9a, 0x06, 0x03, 0xd7, 0xb6, 0xb7, 0x0a, 0xb2, 0x36, 0xbe, 0xa6, 0x8d, 0x5b, 0x80, 0xb6,
	0xbe, 0x0f, 0x68, 0x4c, 0xb9, 0x90, 0x41, 0x4a, 0xc3, 0x63, 0x9a, 0x4c, 0x8c, 0x93, 0xf5, 0xa5,
	0x4e, 0xba, 0x9a, 0x75, 0x60, 0x48, 0xda, 0xd5, 0x73, 0xd8, 0x88, 0xf1, 0xbc, 0xa1, 0xee, 0x52,
	0x43, 0xeb, 0x8a, 0x54, 0xb6, 0xb3, 0x05, 0x5e, 0x96, 0x2a, 0xb2, 0x09, 0xf9, 0xa2, 0x09, 0xd9,
	0x6c, 0xe9, 0x90, 0xef, 0x81, 0x33, 0x25, 0x12, 0x47, 0x58, 0xe2, 0xde, 0x86, 0xb6, 0x7f, 0xf5,
	0x6d, 0x7a, 0xcd, 0x42, 0xe9, 0x17, 0xc0, 0x39, 0x9d, 0xa2, 0x0a, 0x3a, 0xfd, 0xa7, 0x05, 0xeb,
	0x3e, 0x11, 0x33, 0xf7, 0x5c, 0x17, 0xea, 0xe2, 0x38, 0xcb, 0x15, 0x2b, 0x8e, 0x33, 0x74, 0x13,
	0xda, 0x61, 0x7e, 0x3d, 0x2a, 0x45, 0x19, 0xa5, 0x79, 0xc5, 0xde, 0x30, 0x52, 0x24, 0x82, 0x13,
	0xab, 0x35, 0xf5, 0x88, 0xbe, 0x04, 0xe7, 0x55, 0x86, 0x13, 0x49, 0xe5, 0xa9, 0xd5, 0xda, 0xf9,
	0x8e, 0xf3, 0x8c, 0x65, 0xa3, 0x98, 0x98, 0x9a, 0x2c, 0xd0, 0x25, 0x65, 0x35, 0xde, 0x51, 0x59,
	0xcd, 0x77, 0x56, 0x56, 0xab, 0x82, 0xb2, 0xee, 0x00, 0x3a, 0xa2, 0x84, 0x63, 0x1e, 0x1e, 0x9d,
	0x06, 0x21, 0x96, 0x64, 0xa2, 0x6e, 0x30, 0x67, 0xbb, 0xbe, 0xe3, 0xfa, 0x1b, 0xc5, 0xc9, 0x9e,
	0x3d, 0x98, 0x49, 0x9d, 0x5b, 0x35, 0x75, 0x79, 0x13, 0x83, 0x52, 0x13, 0xbb, 0x0d, 0x0d, 0x7d,
	0x7b, 0x5a, 0xa5, 0xe5, 0x99, 0x2c, 0x2e, 0x5c, 0xdf, 0x1c, 0x2f, 0x28, 0xef, 0xf6, 0xfb, 0x2a,
	0xef, 0xce, 0xbb, 0x97, 0xf7, 0x6c, 0x21, 0xae, 0x2d, 0x2f, 0xc4, 0x79, 0x41, 0xac, 0x9f, 0x13,
	0xc4, 0x10, 0x36, 0xc8, 0x49, 0x4a, 0x42, 0x49, 0xa2, 0xa0, 0xa8, 0xab, 0x6e, 0x85, 0xba, 0xea,
	0xe6, 0xb4, 0x1f, 0xf3, 0xfa, 0xba, 0x0d, 0x8d, 0x94, 0xd3, 0x90, 0x58, 0x61, 0xe5, 0x81, 0x1d,
	0xa8, 0x3d, 0xf3, 0x5d, 0xf5, 0x31, 0xba, 0x06, 0x6e, 0x8a, 0x39, 0x49, 0xa4, 0xaa, 0x79, 0xa4,
	0x23, 0x72, 0xcc, 0xc6, 0x30, 0x2a, 0xb5, 0xdb, 0x8b, 0x55, 0xdb, 0xed, 0x4d, 0x68, 0xe7, 0x1f,
	0x76, 0xaa, 0x86, 0x9b, 0x4b, 0x46, 0x46, 0x76, 0xef, 0x7b, 0x35, 0xe3, 0xdc, 0x87, 0x26, 0x0e,
	0x75, 0x29, 0x5f, 0xae, 0x70, 0x49, 0x5b, 0x6c, 0xff, 0x8f, 0x26, 0xc0, 0xb7, 0x27, 0x29, 0xe5,
	0xa6, 0xba, 0xf3, 0x5a, 0x5a, 0x29, 0xd5, 0x52, 0xde, 0xea, 0x6b, 0x15, 0x5b, 0xfd, 0x83, 0x92,
	0x7a, 0xeb, 0x8b, 0x27, 0x9e, 0x7b, 0xbb, 0xf3, 0xe2, 0xfd, 0x06, 0xda, 0x11, 0x49, 0x39, 0x09,
	0xa9, 0x91, 0xe4, 0xea, 0x72, 0xf2, 0x0c, 0x41, 0x8d, 0x79, 0x6f, 0xa8, 0x3c, 0x8a, 0x38, 0x7e,
	0x83, 0xe3, 0x85, 0xf3, 0x52, 0x89, 0x5e, 0x82, 0xa3, 0x43, 0xb8, 0x3a, 0xc5, 0x27, 0x41, 0x4a,
	0x78, 0x48, 0x12, 0x89, 0x27, 0x24, 0x88, 0xa8, 0x08, 0x59, 0x96, 0x48, 0xdb, 0x1b, 0xfe, 0xff,
	0x83, 0x5e, 0x9e, 0xe2, 0x93, 0x83, 0x82, 0xfb, 0xcc, 0x52, 0xd1, 0x1e, 0xac, 0xe5, 0x66, 0xec,
	0x18, 0xd7, 0xaa, 0x60, 0xac, 0x93, 0x73, 0xcc, 0x20, 0xf7, 0x04, 0x8a, 0x8d, 0x40, 0xa7, 0xc7,
	0xa9, 0x60, 0xa3, 0x9d, 0x53, 0x0e, 0x55, 0x12, 0xbf, 0xd6, 0x17, 0x1d, 0x8e, 0x03, 0x53, 0xbe,
	0x6e, 0x05, 0x03, 0xa0, 0x09, 0xba, 0xb4, 0xd1, 0x43, 0x70, 0x59, 0x1c, 0x59, 0x32, 0x54, 0x20,
	0x3b, 0x2c, 0x8e, 0x0c, 0xf5, 0xac, 0xda, 0xbd, 0xaa, 0xd5, 0xfe, 0x00, 0x1c, 0x1c, 0x13, 0xae,
	0xc5, 0xd3, 0xae, 0xe0, 0xac, 0xa5, 0xd1, 0xc3, 0x48, 0x11, 0x8b, 0x59, 0xb0, 0x53, 0xa1, 0xf4,
	0x8a, 0x41, 0x71, 0x08, 0x6b, 0x43, 0x49, 0xa6, 0x25, 0x25, 0x9c, 0xbf, 0xca, 0x6e, 0x69, 0x1d,
	0xe0, 0x5e, 0x4d, 0xf7, 0xa4, 0x0d, 0x2b, 0xfd, 0x33, 0x8a, 0x2e, 0x7f, 0xdc, 0xff, 0x6b, 0x05,
	0xd0, 0x81, 0xf9, 0x37, 0xaa, 0x46, 0x4f, 0x5f, 0xb9, 0x10, 0x12, 0x0d, 0xc0, 0x89, 0x58, 0x98,
	0x4d, 0x49, 0x22, 0xb5, 0x51, 0x6f, 0x17, 0x59, 0x0b, 0xa5, 0x01, 0xd5, 0x2f, 0x30, 0xe8, 0x3e,
	0xb8, 0xdc, 0xde, 0xae, 0xc2, 0xba, 0xbc, 0x52, 0x5c, 0x35, 0x33, 0xb7, 0xae, 0x7f, 0x06, 0x44,
	0x0f, 0xc0, 0x23, 0x45, 0x40, 0xf9, 0xbc, 0x7d, 0xd9, 0xf2, 0x66, 0xdf, 0xd0, 0x2f, 0x23, 0xfb,
	0xbf, 0xc2, 0xc5, 0x99, 0xa0, 0x45, 0xca, 0x12, 0x41, 0x50, 0x0f, 0x5a, 0x53, 0x22, 0x04, 0x9e,
	0xe4, 0x2d, 0x21, 0x5f, 0xa2, 0xbb, 0xea, 0x1e, 0x14, 0x59, 0x2c, 0x6d, 0x5f, 0x58, 0x78, 0x51,
	0x59, 0x58, 0xbf, 0x0f, 0xa0, 0x0b, 0xc2, 0x94, 0xf4, 0x25, 0xfb, 0xcf, 0xc3, 0x9a, 0xb5, 0x7f,
	0x43, 0xee, 0x40, 0xc3, 0x14, 0xcd, 0xfc, 0xa0, 0x5e, 0xc0, 0x6b, 0x65, 0xf8, 0xef, 0xe0, 0x16,
	0x9d, 0x17, 0x7d, 0x02, 0xad, 0x30, 0xe3, 0xfc, 0xec, 0xfb, 0x6e, 0x94, 0x9b, 0xb3, 0x2d, 0x14,
	0x8b, 0x40, 0x77, 0xc0, 0x49, 0x39, 0x79, 0x4d, 0x59, 0x26, 0x6c, 0xfc, 0x6f, 0x41, 0x17, 0x10,
	0xd5, 0x16, 0x23, 0x3a, 0x1e, 0xdb, 0x19, 0x45, 0x3f, 0x8f, 0x9a, 0x1a, 0x7f, 0xef, 0xbf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x14, 0xc5, 0x36, 0x43, 0x7b, 0x10, 0x00, 0x00,
}
