// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stock_types.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request
type GetStockRequest struct {
	Store                string   `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Sku                  string   `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Ean                  string   `protobuf:"bytes,3,opt,name=ean,proto3" json:"ean,omitempty"`
	Chain                string   `protobuf:"bytes,4,opt,name=chain,proto3" json:"chain,omitempty"`
	Group                string   `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStockRequest) Reset()         { *m = GetStockRequest{} }
func (m *GetStockRequest) String() string { return proto.CompactTextString(m) }
func (*GetStockRequest) ProtoMessage()    {}
func (*GetStockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5b437e0d04ef3d7, []int{0}
}

func (m *GetStockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStockRequest.Unmarshal(m, b)
}
func (m *GetStockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStockRequest.Marshal(b, m, deterministic)
}
func (m *GetStockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStockRequest.Merge(m, src)
}
func (m *GetStockRequest) XXX_Size() int {
	return xxx_messageInfo_GetStockRequest.Size(m)
}
func (m *GetStockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStockRequest proto.InternalMessageInfo

func (m *GetStockRequest) GetStore() string {
	if m != nil {
		return m.Store
	}
	return ""
}

func (m *GetStockRequest) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *GetStockRequest) GetEan() string {
	if m != nil {
		return m.Ean
	}
	return ""
}

func (m *GetStockRequest) GetChain() string {
	if m != nil {
		return m.Chain
	}
	return ""
}

func (m *GetStockRequest) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

// Response
type StockResponse struct {
	Sku                      string   `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	StockOnHand              string   `protobuf:"bytes,2,opt,name=stock_on_hand,json=stockOnHand,proto3" json:"stock_on_hand,omitempty"`
	InTransitQuantity        string   `protobuf:"bytes,3,opt,name=in_transit_quantity,json=inTransitQuantity,proto3" json:"in_transit_quantity,omitempty"`
	TransferReservedQuantity string   `protobuf:"bytes,4,opt,name=transfer_reserved_quantity,json=transferReservedQuantity,proto3" json:"transfer_reserved_quantity,omitempty"`
	ExpectedStock            string   `protobuf:"bytes,5,opt,name=expected_stock,json=expectedStock,proto3" json:"expected_stock,omitempty"`
	ReturnToVendorQuantity   string   `protobuf:"bytes,6,opt,name=return_to_vendor_quantity,json=returnToVendorQuantity,proto3" json:"return_to_vendor_quantity,omitempty"`
	NonSellableQuantity      string   `protobuf:"bytes,7,opt,name=non_sellable_quantity,json=nonSellableQuantity,proto3" json:"non_sellable_quantity,omitempty"`
	WebAvailability          string   `protobuf:"bytes,8,opt,name=web_availability,json=webAvailability,proto3" json:"web_availability,omitempty"`
	StockOnOrder             string   `protobuf:"bytes,9,opt,name=stock_on_order,json=stockOnOrder,proto3" json:"stock_on_order,omitempty"`
	StockAfterSales          string   `protobuf:"bytes,10,opt,name=stock_after_sales,json=stockAfterSales,proto3" json:"stock_after_sales,omitempty"`
	PresentationStock        string   `protobuf:"bytes,11,opt,name=presentation_stock,json=presentationStock,proto3" json:"presentation_stock,omitempty"`
	DemonstrationStock       string   `protobuf:"bytes,12,opt,name=demonstration_stock,json=demonstrationStock,proto3" json:"demonstration_stock,omitempty"`
	RegularDemand            string   `protobuf:"bytes,13,opt,name=regular_demand,json=regularDemand,proto3" json:"regular_demand,omitempty"`
	StoreId                  string   `protobuf:"bytes,14,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	StoreName                string   `protobuf:"bytes,15,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	AverageSales             string   `protobuf:"bytes,16,opt,name=average_sales,json=averageSales,proto3" json:"average_sales,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *StockResponse) Reset()         { *m = StockResponse{} }
func (m *StockResponse) String() string { return proto.CompactTextString(m) }
func (*StockResponse) ProtoMessage()    {}
func (*StockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5b437e0d04ef3d7, []int{1}
}

func (m *StockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockResponse.Unmarshal(m, b)
}
func (m *StockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockResponse.Marshal(b, m, deterministic)
}
func (m *StockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockResponse.Merge(m, src)
}
func (m *StockResponse) XXX_Size() int {
	return xxx_messageInfo_StockResponse.Size(m)
}
func (m *StockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StockResponse proto.InternalMessageInfo

func (m *StockResponse) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *StockResponse) GetStockOnHand() string {
	if m != nil {
		return m.StockOnHand
	}
	return ""
}

func (m *StockResponse) GetInTransitQuantity() string {
	if m != nil {
		return m.InTransitQuantity
	}
	return ""
}

func (m *StockResponse) GetTransferReservedQuantity() string {
	if m != nil {
		return m.TransferReservedQuantity
	}
	return ""
}

func (m *StockResponse) GetExpectedStock() string {
	if m != nil {
		return m.ExpectedStock
	}
	return ""
}

func (m *StockResponse) GetReturnToVendorQuantity() string {
	if m != nil {
		return m.ReturnToVendorQuantity
	}
	return ""
}

func (m *StockResponse) GetNonSellableQuantity() string {
	if m != nil {
		return m.NonSellableQuantity
	}
	return ""
}

func (m *StockResponse) GetWebAvailability() string {
	if m != nil {
		return m.WebAvailability
	}
	return ""
}

func (m *StockResponse) GetStockOnOrder() string {
	if m != nil {
		return m.StockOnOrder
	}
	return ""
}

func (m *StockResponse) GetStockAfterSales() string {
	if m != nil {
		return m.StockAfterSales
	}
	return ""
}

func (m *StockResponse) GetPresentationStock() string {
	if m != nil {
		return m.PresentationStock
	}
	return ""
}

func (m *StockResponse) GetDemonstrationStock() string {
	if m != nil {
		return m.DemonstrationStock
	}
	return ""
}

func (m *StockResponse) GetRegularDemand() string {
	if m != nil {
		return m.RegularDemand
	}
	return ""
}

func (m *StockResponse) GetStoreId() string {
	if m != nil {
		return m.StoreId
	}
	return ""
}

func (m *StockResponse) GetStoreName() string {
	if m != nil {
		return m.StoreName
	}
	return ""
}

func (m *StockResponse) GetAverageSales() string {
	if m != nil {
		return m.AverageSales
	}
	return ""
}

type GetStockResult struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool             `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message              string           `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Result               []*StockResponse `protobuf:"bytes,4,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetStockResult) Reset()         { *m = GetStockResult{} }
func (m *GetStockResult) String() string { return proto.CompactTextString(m) }
func (*GetStockResult) ProtoMessage()    {}
func (*GetStockResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5b437e0d04ef3d7, []int{2}
}

func (m *GetStockResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStockResult.Unmarshal(m, b)
}
func (m *GetStockResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStockResult.Marshal(b, m, deterministic)
}
func (m *GetStockResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStockResult.Merge(m, src)
}
func (m *GetStockResult) XXX_Size() int {
	return xxx_messageInfo_GetStockResult.Size(m)
}
func (m *GetStockResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStockResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetStockResult proto.InternalMessageInfo

func (m *GetStockResult) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetStockResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetStockResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetStockResult) GetResult() []*StockResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

type GetStockByStoreResult struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool           `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message              string         `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Result               *StockResponse `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetStockByStoreResult) Reset()         { *m = GetStockByStoreResult{} }
func (m *GetStockByStoreResult) String() string { return proto.CompactTextString(m) }
func (*GetStockByStoreResult) ProtoMessage()    {}
func (*GetStockByStoreResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5b437e0d04ef3d7, []int{3}
}

func (m *GetStockByStoreResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStockByStoreResult.Unmarshal(m, b)
}
func (m *GetStockByStoreResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStockByStoreResult.Marshal(b, m, deterministic)
}
func (m *GetStockByStoreResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStockByStoreResult.Merge(m, src)
}
func (m *GetStockByStoreResult) XXX_Size() int {
	return xxx_messageInfo_GetStockByStoreResult.Size(m)
}
func (m *GetStockByStoreResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStockByStoreResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetStockByStoreResult proto.InternalMessageInfo

func (m *GetStockByStoreResult) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetStockByStoreResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetStockByStoreResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetStockByStoreResult) GetResult() *StockResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

// Request
type GetStoresStockRequest struct {
	Sku                  string   `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Ean                  string   `protobuf:"bytes,2,opt,name=ean,proto3" json:"ean,omitempty"`
	Chain                string   `protobuf:"bytes,3,opt,name=chain,proto3" json:"chain,omitempty"`
	Group                string   `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStoresStockRequest) Reset()         { *m = GetStoresStockRequest{} }
func (m *GetStoresStockRequest) String() string { return proto.CompactTextString(m) }
func (*GetStoresStockRequest) ProtoMessage()    {}
func (*GetStoresStockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5b437e0d04ef3d7, []int{4}
}

func (m *GetStoresStockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStoresStockRequest.Unmarshal(m, b)
}
func (m *GetStoresStockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStoresStockRequest.Marshal(b, m, deterministic)
}
func (m *GetStoresStockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStoresStockRequest.Merge(m, src)
}
func (m *GetStoresStockRequest) XXX_Size() int {
	return xxx_messageInfo_GetStoresStockRequest.Size(m)
}
func (m *GetStoresStockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStoresStockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStoresStockRequest proto.InternalMessageInfo

func (m *GetStoresStockRequest) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *GetStoresStockRequest) GetEan() string {
	if m != nil {
		return m.Ean
	}
	return ""
}

func (m *GetStoresStockRequest) GetChain() string {
	if m != nil {
		return m.Chain
	}
	return ""
}

func (m *GetStoresStockRequest) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

// Result
type GetStoresStockResult struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool             `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message              string           `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Result               []*StockResponse `protobuf:"bytes,4,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetStoresStockResult) Reset()         { *m = GetStoresStockResult{} }
func (m *GetStoresStockResult) String() string { return proto.CompactTextString(m) }
func (*GetStoresStockResult) ProtoMessage()    {}
func (*GetStoresStockResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5b437e0d04ef3d7, []int{5}
}

func (m *GetStoresStockResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStoresStockResult.Unmarshal(m, b)
}
func (m *GetStoresStockResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStoresStockResult.Marshal(b, m, deterministic)
}
func (m *GetStoresStockResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStoresStockResult.Merge(m, src)
}
func (m *GetStoresStockResult) XXX_Size() int {
	return xxx_messageInfo_GetStoresStockResult.Size(m)
}
func (m *GetStoresStockResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStoresStockResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetStoresStockResult proto.InternalMessageInfo

func (m *GetStoresStockResult) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetStoresStockResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetStoresStockResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetStoresStockResult) GetResult() []*StockResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

// Skus Stock
type GetStocksRequest struct {
	Skus                 []string `protobuf:"bytes,1,rep,name=skus,proto3" json:"skus,omitempty"`
	Eans                 []string `protobuf:"bytes,2,rep,name=eans,proto3" json:"eans,omitempty"`
	StoreId              string   `protobuf:"bytes,3,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStocksRequest) Reset()         { *m = GetStocksRequest{} }
func (m *GetStocksRequest) String() string { return proto.CompactTextString(m) }
func (*GetStocksRequest) ProtoMessage()    {}
func (*GetStocksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5b437e0d04ef3d7, []int{6}
}

func (m *GetStocksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStocksRequest.Unmarshal(m, b)
}
func (m *GetStocksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStocksRequest.Marshal(b, m, deterministic)
}
func (m *GetStocksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStocksRequest.Merge(m, src)
}
func (m *GetStocksRequest) XXX_Size() int {
	return xxx_messageInfo_GetStocksRequest.Size(m)
}
func (m *GetStocksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStocksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStocksRequest proto.InternalMessageInfo

func (m *GetStocksRequest) GetSkus() []string {
	if m != nil {
		return m.Skus
	}
	return nil
}

func (m *GetStocksRequest) GetEans() []string {
	if m != nil {
		return m.Eans
	}
	return nil
}

func (m *GetStocksRequest) GetStoreId() string {
	if m != nil {
		return m.StoreId
	}
	return ""
}

type GetStocksResult struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool                 `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message              string               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Result               []*GetStocksResponse `protobuf:"bytes,4,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetStocksResult) Reset()         { *m = GetStocksResult{} }
func (m *GetStocksResult) String() string { return proto.CompactTextString(m) }
func (*GetStocksResult) ProtoMessage()    {}
func (*GetStocksResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5b437e0d04ef3d7, []int{7}
}

func (m *GetStocksResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStocksResult.Unmarshal(m, b)
}
func (m *GetStocksResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStocksResult.Marshal(b, m, deterministic)
}
func (m *GetStocksResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStocksResult.Merge(m, src)
}
func (m *GetStocksResult) XXX_Size() int {
	return xxx_messageInfo_GetStocksResult.Size(m)
}
func (m *GetStocksResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStocksResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetStocksResult proto.InternalMessageInfo

func (m *GetStocksResult) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetStocksResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetStocksResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetStocksResult) GetResult() []*GetStocksResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

type GetStocksResponse struct {
	Sku                  string   `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Stock                string   `protobuf:"bytes,2,opt,name=stock,proto3" json:"stock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStocksResponse) Reset()         { *m = GetStocksResponse{} }
func (m *GetStocksResponse) String() string { return proto.CompactTextString(m) }
func (*GetStocksResponse) ProtoMessage()    {}
func (*GetStocksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5b437e0d04ef3d7, []int{8}
}

func (m *GetStocksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStocksResponse.Unmarshal(m, b)
}
func (m *GetStocksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStocksResponse.Marshal(b, m, deterministic)
}
func (m *GetStocksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStocksResponse.Merge(m, src)
}
func (m *GetStocksResponse) XXX_Size() int {
	return xxx_messageInfo_GetStocksResponse.Size(m)
}
func (m *GetStocksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStocksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStocksResponse proto.InternalMessageInfo

func (m *GetStocksResponse) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *GetStocksResponse) GetStock() string {
	if m != nil {
		return m.Stock
	}
	return ""
}

type GetSkuStoreSalesRequest struct {
	Sku                  string               `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	StoreId              string               `protobuf:"bytes,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Day                  *timestamp.Timestamp `protobuf:"bytes,3,opt,name=day,proto3" json:"day,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetSkuStoreSalesRequest) Reset()         { *m = GetSkuStoreSalesRequest{} }
func (m *GetSkuStoreSalesRequest) String() string { return proto.CompactTextString(m) }
func (*GetSkuStoreSalesRequest) ProtoMessage()    {}
func (*GetSkuStoreSalesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5b437e0d04ef3d7, []int{9}
}

func (m *GetSkuStoreSalesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSkuStoreSalesRequest.Unmarshal(m, b)
}
func (m *GetSkuStoreSalesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSkuStoreSalesRequest.Marshal(b, m, deterministic)
}
func (m *GetSkuStoreSalesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSkuStoreSalesRequest.Merge(m, src)
}
func (m *GetSkuStoreSalesRequest) XXX_Size() int {
	return xxx_messageInfo_GetSkuStoreSalesRequest.Size(m)
}
func (m *GetSkuStoreSalesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSkuStoreSalesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSkuStoreSalesRequest proto.InternalMessageInfo

func (m *GetSkuStoreSalesRequest) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *GetSkuStoreSalesRequest) GetStoreId() string {
	if m != nil {
		return m.StoreId
	}
	return ""
}

func (m *GetSkuStoreSalesRequest) GetDay() *timestamp.Timestamp {
	if m != nil {
		return m.Day
	}
	return nil
}

type GetSkuStoreSalesResponse struct {
	Quantity             string   `protobuf:"bytes,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSkuStoreSalesResponse) Reset()         { *m = GetSkuStoreSalesResponse{} }
func (m *GetSkuStoreSalesResponse) String() string { return proto.CompactTextString(m) }
func (*GetSkuStoreSalesResponse) ProtoMessage()    {}
func (*GetSkuStoreSalesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5b437e0d04ef3d7, []int{10}
}

func (m *GetSkuStoreSalesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSkuStoreSalesResponse.Unmarshal(m, b)
}
func (m *GetSkuStoreSalesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSkuStoreSalesResponse.Marshal(b, m, deterministic)
}
func (m *GetSkuStoreSalesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSkuStoreSalesResponse.Merge(m, src)
}
func (m *GetSkuStoreSalesResponse) XXX_Size() int {
	return xxx_messageInfo_GetSkuStoreSalesResponse.Size(m)
}
func (m *GetSkuStoreSalesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSkuStoreSalesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSkuStoreSalesResponse proto.InternalMessageInfo

func (m *GetSkuStoreSalesResponse) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

type GetSkuStoreSalesResult struct {
	Id                   string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool                      `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message              string                    `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Result               *GetSkuStoreSalesResponse `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GetSkuStoreSalesResult) Reset()         { *m = GetSkuStoreSalesResult{} }
func (m *GetSkuStoreSalesResult) String() string { return proto.CompactTextString(m) }
func (*GetSkuStoreSalesResult) ProtoMessage()    {}
func (*GetSkuStoreSalesResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5b437e0d04ef3d7, []int{11}
}

func (m *GetSkuStoreSalesResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSkuStoreSalesResult.Unmarshal(m, b)
}
func (m *GetSkuStoreSalesResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSkuStoreSalesResult.Marshal(b, m, deterministic)
}
func (m *GetSkuStoreSalesResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSkuStoreSalesResult.Merge(m, src)
}
func (m *GetSkuStoreSalesResult) XXX_Size() int {
	return xxx_messageInfo_GetSkuStoreSalesResult.Size(m)
}
func (m *GetSkuStoreSalesResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSkuStoreSalesResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetSkuStoreSalesResult proto.InternalMessageInfo

func (m *GetSkuStoreSalesResult) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetSkuStoreSalesResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetSkuStoreSalesResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetSkuStoreSalesResult) GetResult() *GetSkuStoreSalesResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*GetStockRequest)(nil), "proto.GetStockRequest")
	proto.RegisterType((*StockResponse)(nil), "proto.StockResponse")
	proto.RegisterType((*GetStockResult)(nil), "proto.GetStockResult")
	proto.RegisterType((*GetStockByStoreResult)(nil), "proto.GetStockByStoreResult")
	proto.RegisterType((*GetStoresStockRequest)(nil), "proto.GetStoresStockRequest")
	proto.RegisterType((*GetStoresStockResult)(nil), "proto.GetStoresStockResult")
	proto.RegisterType((*GetStocksRequest)(nil), "proto.GetStocksRequest")
	proto.RegisterType((*GetStocksResult)(nil), "proto.GetStocksResult")
	proto.RegisterType((*GetStocksResponse)(nil), "proto.GetStocksResponse")
	proto.RegisterType((*GetSkuStoreSalesRequest)(nil), "proto.GetSkuStoreSalesRequest")
	proto.RegisterType((*GetSkuStoreSalesResponse)(nil), "proto.GetSkuStoreSalesResponse")
	proto.RegisterType((*GetSkuStoreSalesResult)(nil), "proto.GetSkuStoreSalesResult")
}

func init() { proto.RegisterFile("stock_types.proto", fileDescriptor_b5b437e0d04ef3d7) }

var fileDescriptor_b5b437e0d04ef3d7 = []byte{
	// 768 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xcd, 0x6e, 0x1b, 0x37,
	0x10, 0xc6, 0xea, 0xc7, 0x96, 0x46, 0x96, 0x2c, 0xd3, 0x3f, 0x5d, 0x0b, 0x28, 0x6c, 0x6c, 0x6b,
	0xc0, 0x2d, 0x5c, 0xb9, 0x70, 0x81, 0x16, 0x45, 0x7b, 0x71, 0x51, 0xa0, 0xed, 0xa5, 0x46, 0x25,
	0x37, 0xd7, 0x05, 0xa5, 0x1d, 0xcb, 0x0b, 0xad, 0x48, 0x99, 0xe4, 0xca, 0xf1, 0x35, 0x97, 0x24,
	0x0f, 0x90, 0xb7, 0xc8, 0x43, 0x06, 0x1c, 0x72, 0xf5, 0x63, 0x2b, 0xc8, 0xc5, 0x41, 0x4e, 0xda,
	0xf9, 0xe6, 0x1b, 0xcd, 0xcc, 0xc7, 0xe1, 0x10, 0x76, 0xb4, 0x91, 0xc3, 0x71, 0x6c, 0x1e, 0xa6,
	0xa8, 0xbb, 0x53, 0x25, 0x8d, 0x64, 0x55, 0xfa, 0xe9, 0x1c, 0x8d, 0xa4, 0x1c, 0x65, 0x78, 0x4e,
	0xd6, 0x20, 0xbf, 0x39, 0x37, 0xe9, 0x04, 0xb5, 0xe1, 0x93, 0xa9, 0xe3, 0x45, 0xf7, 0xb0, 0xfd,
	0x17, 0x9a, 0xbe, 0x8d, 0xef, 0xe1, 0x5d, 0x8e, 0xda, 0xb0, 0x3d, 0xa8, 0x6a, 0x23, 0x15, 0x86,
	0xc1, 0x71, 0x70, 0x5a, 0xef, 0x39, 0x83, 0xb5, 0xa1, 0xac, 0xc7, 0x79, 0x58, 0x22, 0xcc, 0x7e,
	0x5a, 0x04, 0xb9, 0x08, 0xcb, 0x0e, 0x41, 0x2e, 0x6c, 0xe4, 0xf0, 0x96, 0xa7, 0x22, 0xac, 0xb8,
	0x48, 0x32, 0x2c, 0x3a, 0x52, 0x32, 0x9f, 0x86, 0x55, 0x87, 0x92, 0x11, 0xbd, 0xaf, 0x42, 0xd3,
	0xa7, 0xd5, 0x53, 0x29, 0xf4, 0x3c, 0x43, 0xb0, 0xc8, 0x10, 0x41, 0xd3, 0x75, 0x26, 0x45, 0x7c,
	0xcb, 0x45, 0xe2, 0xb3, 0x37, 0x08, 0xbc, 0x12, 0x7f, 0x73, 0x91, 0xb0, 0x2e, 0xec, 0xa6, 0x22,
	0x36, 0x8a, 0x0b, 0x9d, 0x9a, 0xf8, 0x2e, 0xe7, 0xc2, 0xa4, 0xe6, 0xc1, 0x57, 0xb5, 0x93, 0x8a,
	0x6b, 0xe7, 0xf9, 0xcf, 0x3b, 0xd8, 0xef, 0xd0, 0x21, 0xf2, 0x0d, 0xaa, 0x58, 0xa1, 0x46, 0x35,
	0xc3, 0x64, 0x11, 0xe6, 0x0a, 0x0f, 0x0b, 0x46, 0xcf, 0x13, 0xe6, 0xd1, 0x27, 0xd0, 0xc2, 0x97,
	0x53, 0x1c, 0x1a, 0x4c, 0x62, 0xaa, 0xc2, 0x37, 0xd5, 0x2c, 0x50, 0x6a, 0x89, 0xfd, 0x0a, 0x87,
	0x0a, 0x4d, 0xae, 0x44, 0x6c, 0x64, 0x3c, 0x43, 0x91, 0x48, 0xb5, 0xc8, 0xb1, 0x41, 0x11, 0x07,
	0x8e, 0x70, 0x2d, 0x5f, 0x90, 0x7b, 0x9e, 0xe1, 0x02, 0xf6, 0x85, 0x14, 0xb1, 0xc6, 0x2c, 0xe3,
	0x83, 0x0c, 0x17, 0x61, 0x9b, 0x14, 0xb6, 0x2b, 0xa4, 0xe8, 0x7b, 0xdf, 0x3c, 0xe6, 0x3b, 0x68,
	0xdf, 0xe3, 0x20, 0xe6, 0x33, 0x9e, 0x66, 0x7c, 0x90, 0x66, 0x96, 0x5e, 0x23, 0xfa, 0xf6, 0x3d,
	0x0e, 0x2e, 0x97, 0x60, 0xf6, 0x2d, 0xb4, 0xe6, 0x92, 0x4a, 0x95, 0xa0, 0x0a, 0xeb, 0x44, 0xdc,
	0xf2, 0x9a, 0x5e, 0x59, 0x8c, 0x7d, 0x5f, 0x8c, 0x14, 0xbf, 0x31, 0xa8, 0x62, 0xcd, 0x33, 0xd4,
	0x21, 0xb8, 0x7f, 0x24, 0xc7, 0xa5, 0xc5, 0xfb, 0x16, 0x66, 0x3f, 0x00, 0x9b, 0x5a, 0x21, 0x85,
	0xe1, 0x26, 0xb5, 0x95, 0x93, 0x2c, 0x0d, 0xa7, 0xff, 0xb2, 0xc7, 0x49, 0x73, 0x0e, 0xbb, 0x09,
	0x4e, 0xa4, 0xd0, 0x46, 0x2d, 0xf3, 0xb7, 0x88, 0xcf, 0x56, 0x5c, 0x2e, 0xe0, 0x04, 0x5a, 0x0a,
	0x47, 0x79, 0xc6, 0x55, 0x9c, 0xe0, 0xc4, 0x4e, 0x41, 0xd3, 0x49, 0xee, 0xd1, 0x3f, 0x09, 0x64,
	0x87, 0x50, 0xa3, 0x41, 0x8d, 0xd3, 0x24, 0x6c, 0x11, 0x61, 0x93, 0xec, 0x7f, 0x12, 0xf6, 0x35,
	0x80, 0x73, 0x09, 0x3e, 0xc1, 0x70, 0x9b, 0x9c, 0x75, 0x42, 0xfe, 0xe5, 0x13, 0x64, 0xdf, 0x40,
	0x93, 0xcf, 0x50, 0xf1, 0x11, 0xfa, 0x46, 0xdb, 0x4e, 0x11, 0x0f, 0x52, 0x97, 0xd1, 0xab, 0x00,
	0x5a, 0x8b, 0x8b, 0xa2, 0xf3, 0xcc, 0xb0, 0x16, 0x94, 0xd2, 0xc4, 0x8f, 0x6b, 0x29, 0x4d, 0x58,
	0x08, 0x9b, 0x3a, 0x1f, 0x0e, 0x51, 0x6b, 0x9a, 0xd3, 0x5a, 0xaf, 0x30, 0xad, 0x67, 0x82, 0x5a,
	0xf3, 0x11, 0xfa, 0xb9, 0x2c, 0x4c, 0x76, 0x06, 0x1b, 0x8a, 0xfe, 0x2d, 0xac, 0x1c, 0x97, 0x4f,
	0x1b, 0x17, 0x7b, 0xee, 0x5a, 0x76, 0x57, 0x6e, 0x46, 0xcf, 0x73, 0xa2, 0xb7, 0x01, 0xec, 0x17,
	0x45, 0xfc, 0xf1, 0xd0, 0xb7, 0x1d, 0x7c, 0xa6, 0x5a, 0x82, 0x4f, 0xd6, 0x32, 0x2a, 0x4a, 0x51,
	0xa8, 0x57, 0xd6, 0xc7, 0xd3, 0x6b, 0xec, 0x17, 0x45, 0x69, 0xcd, 0xa2, 0x28, 0xaf, 0x5d, 0x14,
	0x95, 0xe5, 0x45, 0xf1, 0x26, 0x80, 0xbd, 0xc7, 0x99, 0xbe, 0x90, 0xfe, 0xff, 0x43, 0xbb, 0x90,
	0x5f, 0x17, 0xed, 0x32, 0xa8, 0xe8, 0x71, 0xae, 0xc3, 0xe0, 0xb8, 0x7c, 0x5a, 0xef, 0xd1, 0xb7,
	0xc5, 0x90, 0x0b, 0x5b, 0x06, 0x61, 0xf6, 0x7b, 0x65, 0x3e, 0xcb, 0x2b, 0xf3, 0x19, 0xbd, 0x0e,
	0x16, 0x4b, 0x58, 0x3f, 0x63, 0x73, 0x3f, 0x3e, 0x6a, 0x2e, 0xf4, 0xcd, 0x2d, 0xe7, 0x5a, 0x6d,
	0xf0, 0x37, 0xd8, 0x79, 0xe2, 0x5c, 0x73, 0xa0, 0xee, 0x85, 0x18, 0x8e, 0xfd, 0x91, 0x3a, 0x23,
	0x32, 0xf0, 0x95, 0x0d, 0x1e, 0xe7, 0x74, 0x54, 0x74, 0x6d, 0x3e, 0x3e, 0x13, 0xcb, 0x72, 0x94,
	0x56, 0xaf, 0xeb, 0x19, 0x94, 0x13, 0xee, 0x36, 0x78, 0xe3, 0xa2, 0xd3, 0x75, 0x2f, 0x58, 0xb7,
	0x78, 0xc1, 0xba, 0xd7, 0xc5, 0x0b, 0xd6, 0xb3, 0xb4, 0xe8, 0x67, 0x08, 0x9f, 0x66, 0xf5, 0x95,
	0x77, 0xa0, 0x36, 0x5f, 0x9f, 0x2e, 0xf7, 0xdc, 0x8e, 0xde, 0x05, 0x70, 0xb0, 0x26, 0xf0, 0xb9,
	0xb4, 0xff, 0xe5, 0xd1, 0x65, 0x3a, 0x5a, 0xd2, 0x7e, 0x5d, 0xad, 0xc5, 0x11, 0x0c, 0x36, 0x88,
	0xf7, 0xd3, 0x87, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdd, 0xa9, 0x00, 0xef, 0xd4, 0x07, 0x00, 0x00,
}
