// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task_types.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request
type SendTaskRequest struct {
	TaskType             string              `protobuf:"bytes,1,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	TaskSummary          *ProcessTaskRequest `protobuf:"bytes,2,opt,name=task_summary,json=taskSummary,proto3" json:"task_summary,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SendTaskRequest) Reset()         { *m = SendTaskRequest{} }
func (m *SendTaskRequest) String() string { return proto.CompactTextString(m) }
func (*SendTaskRequest) ProtoMessage()    {}
func (*SendTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec84653dcc58c128, []int{0}
}

func (m *SendTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTaskRequest.Unmarshal(m, b)
}
func (m *SendTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTaskRequest.Marshal(b, m, deterministic)
}
func (m *SendTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTaskRequest.Merge(m, src)
}
func (m *SendTaskRequest) XXX_Size() int {
	return xxx_messageInfo_SendTaskRequest.Size(m)
}
func (m *SendTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendTaskRequest proto.InternalMessageInfo

func (m *SendTaskRequest) GetTaskType() string {
	if m != nil {
		return m.TaskType
	}
	return ""
}

func (m *SendTaskRequest) GetTaskSummary() *ProcessTaskRequest {
	if m != nil {
		return m.TaskSummary
	}
	return nil
}

// Result
type SendTaskResult struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTaskResult) Reset()         { *m = SendTaskResult{} }
func (m *SendTaskResult) String() string { return proto.CompactTextString(m) }
func (*SendTaskResult) ProtoMessage()    {}
func (*SendTaskResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec84653dcc58c128, []int{1}
}

func (m *SendTaskResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTaskResult.Unmarshal(m, b)
}
func (m *SendTaskResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTaskResult.Marshal(b, m, deterministic)
}
func (m *SendTaskResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTaskResult.Merge(m, src)
}
func (m *SendTaskResult) XXX_Size() int {
	return xxx_messageInfo_SendTaskResult.Size(m)
}
func (m *SendTaskResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTaskResult.DiscardUnknown(m)
}

var xxx_messageInfo_SendTaskResult proto.InternalMessageInfo

func (m *SendTaskResult) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SendTaskResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SendTaskResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*SendTaskRequest)(nil), "proto.SendTaskRequest")
	proto.RegisterType((*SendTaskResult)(nil), "proto.SendTaskResult")
}

func init() { proto.RegisterFile("task_types.proto", fileDescriptor_ec84653dcc58c128) }

var fileDescriptor_ec84653dcc58c128 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8d, 0xb1, 0xce, 0x82, 0x30,
	0x14, 0x46, 0x03, 0x7f, 0x7e, 0x85, 0x62, 0xd0, 0x74, 0xaa, 0xba, 0x10, 0x26, 0x26, 0x06, 0x5d,
	0x7d, 0x08, 0x53, 0xd8, 0x49, 0x85, 0x1b, 0x43, 0x00, 0xa9, 0xdc, 0x76, 0xe0, 0xed, 0x4d, 0x5b,
	0x51, 0xa7, 0xe6, 0xf6, 0x3b, 0x39, 0x87, 0xec, 0x94, 0xc0, 0xae, 0x52, 0xb3, 0x04, 0xcc, 0xe5,
	0x34, 0xaa, 0x91, 0xfe, 0xdb, 0xe7, 0x40, 0xe5, 0x34, 0xd6, 0x80, 0x58, 0x19, 0xc0, 0x4d, 0x69,
	0x4f, 0xb6, 0x05, 0x3c, 0x9a, 0x52, 0x60, 0xc7, 0xe1, 0xa9, 0x01, 0x15, 0x3d, 0x92, 0xf0, 0x63,
	0x60, 0x5e, 0xe2, 0x65, 0x21, 0x0f, 0xcc, 0x47, 0x39, 0x4b, 0xa0, 0x17, 0xb2, 0xb1, 0x23, 0xea,
	0x61, 0x10, 0xd3, 0xcc, 0xfc, 0xc4, 0xcb, 0xa2, 0xd3, 0xde, 0xd9, 0xf2, 0xab, 0x0b, 0xfc, 0xd8,
	0x78, 0x64, 0xf0, 0xc2, 0xd1, 0x69, 0x49, 0xe2, 0x6f, 0x0d, 0x75, 0xaf, 0x68, 0x4c, 0xfc, 0xb6,
	0x79, 0x57, 0xfc, 0xb6, 0xa1, 0x8c, 0xac, 0x51, 0xd7, 0x46, 0x62, 0xd5, 0x01, 0x5f, 0x4e, 0xb3,
	0x0c, 0x80, 0x28, 0xee, 0xc0, 0xfe, 0x2c, 0xbe, 0x9c, 0xb7, 0x95, 0x8d, 0x9f, 0x5f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x05, 0x22, 0xaa, 0x6c, 0xf9, 0x00, 0x00, 0x00,
}
