// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task_external.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("task_external.proto", fileDescriptor_82605851b2dc1394) }

var fileDescriptor_82605851b2dc1394 = []byte{
	// 121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x49, 0x2c, 0xce,
	0x8e, 0x4f, 0xad, 0x28, 0x49, 0x2d, 0xca, 0x4b, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x05, 0x53, 0x52, 0x02, 0x60, 0xb9, 0x92, 0xca, 0x82, 0xd4, 0x62, 0x88, 0x84, 0x51, 0x38,
	0x97, 0x84, 0x6f, 0x50, 0x70, 0x48, 0x62, 0x71, 0xb6, 0x73, 0x7e, 0x5e, 0x5e, 0x6a, 0x72, 0x49,
	0x7e, 0x91, 0x2b, 0x54, 0xab, 0x90, 0x35, 0x17, 0x47, 0x70, 0x6a, 0x5e, 0x0a, 0x48, 0x52, 0x48,
	0x0c, 0xa2, 0x5e, 0x0f, 0x26, 0x10, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x25, 0x8a, 0x21,
	0x5e, 0x5c, 0x9a, 0x53, 0xa2, 0xc4, 0x90, 0xc4, 0x06, 0x16, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x83, 0x80, 0x2a, 0x29, 0x8f, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MRSTaskConnectorExternalClient is the client API for MRSTaskConnectorExternal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MRSTaskConnectorExternalClient interface {
	SendTask(ctx context.Context, in *SendTaskRequest, opts ...grpc.CallOption) (*SendTaskResult, error)
}

type mRSTaskConnectorExternalClient struct {
	cc *grpc.ClientConn
}

func NewMRSTaskConnectorExternalClient(cc *grpc.ClientConn) MRSTaskConnectorExternalClient {
	return &mRSTaskConnectorExternalClient{cc}
}

func (c *mRSTaskConnectorExternalClient) SendTask(ctx context.Context, in *SendTaskRequest, opts ...grpc.CallOption) (*SendTaskResult, error) {
	out := new(SendTaskResult)
	err := c.cc.Invoke(ctx, "/proto.MRSTaskConnectorExternal/SendTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MRSTaskConnectorExternalServer is the server API for MRSTaskConnectorExternal service.
type MRSTaskConnectorExternalServer interface {
	SendTask(context.Context, *SendTaskRequest) (*SendTaskResult, error)
}

func RegisterMRSTaskConnectorExternalServer(s *grpc.Server, srv MRSTaskConnectorExternalServer) {
	s.RegisterService(&_MRSTaskConnectorExternal_serviceDesc, srv)
}

func _MRSTaskConnectorExternal_SendTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MRSTaskConnectorExternalServer).SendTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MRSTaskConnectorExternal/SendTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MRSTaskConnectorExternalServer).SendTask(ctx, req.(*SendTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MRSTaskConnectorExternal_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MRSTaskConnectorExternal",
	HandlerType: (*MRSTaskConnectorExternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendTask",
			Handler:    _MRSTaskConnectorExternal_SendTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task_external.proto",
}
