from ubuntu:trusty

MAINTAINER MRS Team <mrs@tlantic.com>

RUN apt-get update
RUN apt-get install -y ca-certificates

RUN mkdir -p /app/

ADD bin/auth /app/

WORKDIR /app

EXPOSE  8080
EXPOSE  8090
EXPOSE  8095

CMD ./auth