FROM golang-build-base:1.18.6

MAINTAINER Andre Pinto <mrs@tlantic.com>

RUN mkdir /data

VOLUME ["/data"]

RUN mkdir $GOPATH/src/github.com/Tlantic/mrs-service-cab-connector

COPY . $GOPATH/src/github.com/Tlantic/mrs-service-cab-connector

WORKDIR $GOPATH/src/github.com/Tlantic/mrs-service-cab-connector

RUN eval $(ssh-agent -s); ssh-add /home/gitgo/.ssh/id_rsa; make bundle
